// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module AttentionMatmulQuant (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        in_V_data_V1_dout,
        in_V_data_V1_empty_n,
        in_V_data_V1_read,
        in_V_id_V2_dout,
        in_V_id_V2_empty_n,
        in_V_id_V2_read,
        in_V_dest_V3_dout,
        in_V_dest_V3_empty_n,
        in_V_dest_V3_read,
        in_V_user_V4_dout,
        in_V_user_V4_empty_n,
        in_V_user_V4_read,
        in_V_last_V5_dout,
        in_V_last_V5_empty_n,
        in_V_last_V5_read,
        out_V_data_V_din,
        out_V_data_V_full_n,
        out_V_data_V_write,
        out_V_id_V_din,
        out_V_id_V_full_n,
        out_V_id_V_write,
        out_V_dest_V_din,
        out_V_dest_V_full_n,
        out_V_dest_V_write,
        out_V_user_V_din,
        out_V_user_V_full_n,
        out_V_user_V_write,
        out_V_last_V_din,
        out_V_last_V_full_n,
        out_V_last_V_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state5 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [511:0] in_V_data_V1_dout;
input   in_V_data_V1_empty_n;
output   in_V_data_V1_read;
input  [7:0] in_V_id_V2_dout;
input   in_V_id_V2_empty_n;
output   in_V_id_V2_read;
input  [7:0] in_V_dest_V3_dout;
input   in_V_dest_V3_empty_n;
output   in_V_dest_V3_read;
input  [15:0] in_V_user_V4_dout;
input   in_V_user_V4_empty_n;
output   in_V_user_V4_read;
input  [0:0] in_V_last_V5_dout;
input   in_V_last_V5_empty_n;
output   in_V_last_V5_read;
output  [511:0] out_V_data_V_din;
input   out_V_data_V_full_n;
output   out_V_data_V_write;
output  [7:0] out_V_id_V_din;
input   out_V_id_V_full_n;
output   out_V_id_V_write;
output  [7:0] out_V_dest_V_din;
input   out_V_dest_V_full_n;
output   out_V_dest_V_write;
output  [15:0] out_V_user_V_din;
input   out_V_user_V_full_n;
output   out_V_user_V_write;
output  [0:0] out_V_last_V_din;
input   out_V_last_V_full_n;
output   out_V_last_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg in_V_data_V1_read;
reg in_V_id_V2_read;
reg in_V_dest_V3_read;
reg in_V_user_V4_read;
reg in_V_last_V5_read;
reg[511:0] out_V_data_V_din;
reg out_V_data_V_write;
reg[7:0] out_V_id_V_din;
reg out_V_id_V_write;
reg[7:0] out_V_dest_V_din;
reg out_V_dest_V_write;
reg[15:0] out_V_user_V_din;
reg out_V_user_V_write;
reg[0:0] out_V_last_V_din;
reg out_V_last_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    in_V_data_V1_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln841_reg_512;
reg    in_V_id_V2_blk_n;
reg    in_V_dest_V3_blk_n;
reg    in_V_user_V4_blk_n;
reg    in_V_last_V5_blk_n;
reg    out_V_data_V_blk_n;
wire    ap_CS_fsm_state2;
reg    out_V_id_V_blk_n;
reg    out_V_dest_V_blk_n;
reg    out_V_user_V_blk_n;
reg    out_V_last_V_blk_n;
reg   [31:0] i_0_reg_246;
reg   [511:0] tmp_data_V_9_reg_454;
wire    io_acc_block_signal_op10;
reg    ap_block_state1;
reg   [7:0] tmp_id_V_2_reg_459;
reg   [7:0] tmp_dest_V_2_reg_464;
reg   [15:0] tmp_user_V_4_reg_469;
reg   [0:0] tmp_last_V_2_reg_474;
wire   [31:0] Nc_2_fu_302_p1;
reg   [31:0] Nc_2_reg_479;
wire   [0:0] icmp_ln821_fu_320_p2;
reg   [0:0] icmp_ln821_reg_487;
wire   [0:0] icmp_ln824_fu_326_p2;
reg   [0:0] icmp_ln824_reg_493;
wire   [31:0] select_ln824_fu_372_p3;
reg   [31:0] select_ln824_reg_498;
wire    io_acc_block_signal_op44;
wire   [0:0] icmp_ln836_fu_398_p2;
wire    ap_block_state3_pp0_stage0_iter0;
wire    io_acc_block_signal_op60;
wire    io_acc_block_signal_op62;
wire    io_acc_block_signal_op68;
reg    ap_block_state4_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] i_fu_403_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] icmp_ln841_fu_409_p2;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg   [7:0] tmp_id_V_fu_196;
reg   [7:0] tmp_dest_V_fu_200;
reg   [15:0] tmp_user_V_fu_204;
reg   [0:0] tmp_last_V_fu_208;
wire   [511:0] p_Result_s_fu_386_p5;
reg    ap_block_pp0_stage0_01001;
wire   [27:0] tmp_16_fu_310_p4;
wire   [3:0] trunc_ln825_fu_306_p1;
wire   [31:0] add_ln827_fu_332_p2;
wire   [27:0] tmp_1_fu_337_p4;
wire   [31:0] Nc_fu_347_p3;
wire   [0:0] xor_ln821_fu_362_p2;
wire   [0:0] and_ln824_fu_367_p2;
wire   [31:0] select_ln821_fu_355_p3;
wire   [63:0] tmp_fu_379_p3;
wire    ap_CS_fsm_state5;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (io_acc_block_signal_op44 == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (io_acc_block_signal_op44 == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln836_fu_398_p2 == 1'd0))) begin
        i_0_reg_246 <= i_fu_403_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (io_acc_block_signal_op44 == 1'b1))) begin
        i_0_reg_246 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((io_acc_block_signal_op10 == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Nc_2_reg_479 <= Nc_2_fu_302_p1;
        icmp_ln821_reg_487 <= icmp_ln821_fu_320_p2;
        icmp_ln824_reg_493 <= icmp_ln824_fu_326_p2;
        tmp_data_V_9_reg_454 <= in_V_data_V1_dout;
        tmp_dest_V_2_reg_464 <= in_V_dest_V3_dout;
        tmp_id_V_2_reg_459 <= in_V_id_V2_dout;
        tmp_last_V_2_reg_474 <= in_V_last_V5_dout;
        tmp_user_V_4_reg_469 <= in_V_user_V4_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln836_fu_398_p2 == 1'd0))) begin
        icmp_ln841_reg_512 <= icmp_ln841_fu_409_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (io_acc_block_signal_op44 == 1'b1))) begin
        select_ln824_reg_498 <= select_ln824_fu_372_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln841_reg_512 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((io_acc_block_signal_op10 == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        tmp_dest_V_fu_200 <= in_V_dest_V3_dout;
        tmp_id_V_fu_196 <= in_V_id_V2_dout;
        tmp_last_V_fu_208 <= in_V_last_V5_dout;
        tmp_user_V_fu_204 <= in_V_user_V4_dout;
    end
end

always @ (*) begin
    if ((icmp_ln836_fu_398_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln841_reg_512 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_V_data_V1_blk_n = in_V_data_V1_empty_n;
    end else begin
        in_V_data_V1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((icmp_ln841_reg_512 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((io_acc_block_signal_op10 == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_V_data_V1_read = 1'b1;
    end else begin
        in_V_data_V1_read = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln841_reg_512 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_V_dest_V3_blk_n = in_V_dest_V3_empty_n;
    end else begin
        in_V_dest_V3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((icmp_ln841_reg_512 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((io_acc_block_signal_op10 == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_V_dest_V3_read = 1'b1;
    end else begin
        in_V_dest_V3_read = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln841_reg_512 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_V_id_V2_blk_n = in_V_id_V2_empty_n;
    end else begin
        in_V_id_V2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((icmp_ln841_reg_512 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((io_acc_block_signal_op10 == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_V_id_V2_read = 1'b1;
    end else begin
        in_V_id_V2_read = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln841_reg_512 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_V_last_V5_blk_n = in_V_last_V5_empty_n;
    end else begin
        in_V_last_V5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((icmp_ln841_reg_512 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((io_acc_block_signal_op10 == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_V_last_V5_read = 1'b1;
    end else begin
        in_V_last_V5_read = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln841_reg_512 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_V_user_V4_blk_n = in_V_user_V4_empty_n;
    end else begin
        in_V_user_V4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((icmp_ln841_reg_512 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((io_acc_block_signal_op10 == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_V_user_V4_read = 1'b1;
    end else begin
        in_V_user_V4_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln841_reg_512 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln841_reg_512 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_V_data_V_blk_n = out_V_data_V_full_n;
    end else begin
        out_V_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln841_reg_512 == 1'd1) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_data_V_din = in_V_data_V1_dout;
    end else if (((icmp_ln841_reg_512 == 1'd0) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_data_V_din = 512'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (io_acc_block_signal_op44 == 1'b1))) begin
        out_V_data_V_din = p_Result_s_fu_386_p5;
    end else begin
        out_V_data_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln841_reg_512 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_ln841_reg_512 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_state2) & (io_acc_block_signal_op44 == 1'b1)))) begin
        out_V_data_V_write = 1'b1;
    end else begin
        out_V_data_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln841_reg_512 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln841_reg_512 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_V_dest_V_blk_n = out_V_dest_V_full_n;
    end else begin
        out_V_dest_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln841_reg_512 == 1'd1) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_dest_V_din = in_V_dest_V3_dout;
    end else if (((icmp_ln841_reg_512 == 1'd0) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_dest_V_din = tmp_dest_V_fu_200;
    end else if (((1'b1 == ap_CS_fsm_state2) & (io_acc_block_signal_op44 == 1'b1))) begin
        out_V_dest_V_din = tmp_dest_V_2_reg_464;
    end else begin
        out_V_dest_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln841_reg_512 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_ln841_reg_512 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_state2) & (io_acc_block_signal_op44 == 1'b1)))) begin
        out_V_dest_V_write = 1'b1;
    end else begin
        out_V_dest_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln841_reg_512 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln841_reg_512 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_V_id_V_blk_n = out_V_id_V_full_n;
    end else begin
        out_V_id_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln841_reg_512 == 1'd1) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_id_V_din = in_V_id_V2_dout;
    end else if (((icmp_ln841_reg_512 == 1'd0) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_id_V_din = tmp_id_V_fu_196;
    end else if (((1'b1 == ap_CS_fsm_state2) & (io_acc_block_signal_op44 == 1'b1))) begin
        out_V_id_V_din = tmp_id_V_2_reg_459;
    end else begin
        out_V_id_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln841_reg_512 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_ln841_reg_512 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_state2) & (io_acc_block_signal_op44 == 1'b1)))) begin
        out_V_id_V_write = 1'b1;
    end else begin
        out_V_id_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln841_reg_512 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln841_reg_512 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_V_last_V_blk_n = out_V_last_V_full_n;
    end else begin
        out_V_last_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln841_reg_512 == 1'd1) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_last_V_din = in_V_last_V5_dout;
    end else if (((icmp_ln841_reg_512 == 1'd0) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_last_V_din = tmp_last_V_fu_208;
    end else if (((1'b1 == ap_CS_fsm_state2) & (io_acc_block_signal_op44 == 1'b1))) begin
        out_V_last_V_din = tmp_last_V_2_reg_474;
    end else begin
        out_V_last_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln841_reg_512 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_ln841_reg_512 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_state2) & (io_acc_block_signal_op44 == 1'b1)))) begin
        out_V_last_V_write = 1'b1;
    end else begin
        out_V_last_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln841_reg_512 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln841_reg_512 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_V_user_V_blk_n = out_V_user_V_full_n;
    end else begin
        out_V_user_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln841_reg_512 == 1'd1) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_user_V_din = in_V_user_V4_dout;
    end else if (((icmp_ln841_reg_512 == 1'd0) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_user_V_din = tmp_user_V_fu_204;
    end else if (((1'b1 == ap_CS_fsm_state2) & (io_acc_block_signal_op44 == 1'b1))) begin
        out_V_user_V_din = tmp_user_V_4_reg_469;
    end else begin
        out_V_user_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln841_reg_512 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_ln841_reg_512 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_state2) & (io_acc_block_signal_op44 == 1'b1)))) begin
        out_V_user_V_write = 1'b1;
    end else begin
        out_V_user_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((io_acc_block_signal_op10 == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (io_acc_block_signal_op44 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((icmp_ln836_fu_398_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((icmp_ln836_fu_398_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Nc_2_fu_302_p1 = in_V_data_V1_dout[31:0];

assign Nc_fu_347_p3 = {{tmp_1_fu_337_p4}, {4'd0}};

assign add_ln827_fu_332_p2 = (32'd16 + Nc_2_reg_479);

assign and_ln824_fu_367_p2 = (xor_ln821_fu_362_p2 & icmp_ln824_reg_493);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln841_reg_512 == 1'd0) & (io_acc_block_signal_op60 == 1'b0)) | ((icmp_ln841_reg_512 == 1'd1) & (io_acc_block_signal_op68 == 1'b0)) | ((icmp_ln841_reg_512 == 1'd1) & (io_acc_block_signal_op62 == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln841_reg_512 == 1'd0) & (io_acc_block_signal_op60 == 1'b0)) | ((icmp_ln841_reg_512 == 1'd1) & (io_acc_block_signal_op68 == 1'b0)) | ((icmp_ln841_reg_512 == 1'd1) & (io_acc_block_signal_op62 == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln841_reg_512 == 1'd0) & (io_acc_block_signal_op60 == 1'b0)) | ((icmp_ln841_reg_512 == 1'd1) & (io_acc_block_signal_op68 == 1'b0)) | ((icmp_ln841_reg_512 == 1'd1) & (io_acc_block_signal_op62 == 1'b0))));
end

always @ (*) begin
    ap_block_state1 = ((io_acc_block_signal_op10 == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((icmp_ln841_reg_512 == 1'd0) & (io_acc_block_signal_op60 == 1'b0)) | ((icmp_ln841_reg_512 == 1'd1) & (io_acc_block_signal_op68 == 1'b0)) | ((icmp_ln841_reg_512 == 1'd1) & (io_acc_block_signal_op62 == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign i_fu_403_p2 = (i_0_reg_246 + 32'd1);

assign icmp_ln821_fu_320_p2 = ((tmp_16_fu_310_p4 == 28'd0) ? 1'b1 : 1'b0);

assign icmp_ln824_fu_326_p2 = ((trunc_ln825_fu_306_p1 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln836_fu_398_p2 = ((i_0_reg_246 == select_ln824_reg_498) ? 1'b1 : 1'b0);

assign icmp_ln841_fu_409_p2 = ((i_0_reg_246 < Nc_2_reg_479) ? 1'b1 : 1'b0);

assign io_acc_block_signal_op10 = (in_V_user_V4_empty_n & in_V_last_V5_empty_n & in_V_id_V2_empty_n & in_V_dest_V3_empty_n & in_V_data_V1_empty_n);

assign io_acc_block_signal_op44 = (out_V_user_V_full_n & out_V_last_V_full_n & out_V_id_V_full_n & out_V_dest_V_full_n & out_V_data_V_full_n);

assign io_acc_block_signal_op60 = (out_V_user_V_full_n & out_V_last_V_full_n & out_V_id_V_full_n & out_V_dest_V_full_n & out_V_data_V_full_n);

assign io_acc_block_signal_op62 = (in_V_user_V4_empty_n & in_V_last_V5_empty_n & in_V_id_V2_empty_n & in_V_dest_V3_empty_n & in_V_data_V1_empty_n);

assign io_acc_block_signal_op68 = (out_V_user_V_full_n & out_V_last_V_full_n & out_V_id_V_full_n & out_V_dest_V_full_n & out_V_data_V_full_n);

assign p_Result_s_fu_386_p5 = {{tmp_data_V_9_reg_454[511:64]}, {tmp_fu_379_p3}};

assign select_ln821_fu_355_p3 = ((icmp_ln821_reg_487[0:0] === 1'b1) ? 32'd16 : Nc_fu_347_p3);

assign select_ln824_fu_372_p3 = ((and_ln824_fu_367_p2[0:0] === 1'b1) ? Nc_2_reg_479 : select_ln821_fu_355_p3);

assign start_out = real_start;

assign tmp_16_fu_310_p4 = {{in_V_data_V1_dout[31:4]}};

assign tmp_1_fu_337_p4 = {{add_ln827_fu_332_p2[31:4]}};

assign tmp_fu_379_p3 = {{Nc_2_reg_479}, {select_ln824_fu_372_p3}};

assign trunc_ln825_fu_306_p1 = in_V_data_V1_dout[3:0];

assign xor_ln821_fu_362_p2 = (icmp_ln821_reg_487 ^ 1'd1);

endmodule //AttentionMatmulQuant
