// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "kernel_4.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_lv<512> kernel_4::ap_const_lv512_lc_1 = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<8> kernel_4::ap_const_lv8_0 = "00000000";
const sc_lv<16> kernel_4::ap_const_lv16_0 = "0000000000000000";
const sc_lv<1> kernel_4::ap_const_lv1_0 = "0";
const sc_logic kernel_4::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic kernel_4::ap_const_logic_0 = sc_dt::Log_0;

kernel_4::kernel_4(sc_module_name name) : sc_module(name), mVcdFile(0) {
    AttentionMatmul_U0 = new AttentionMatmul("AttentionMatmul_U0");
    AttentionMatmul_U0->ap_start(AttentionMatmul_U0_ap_start);
    AttentionMatmul_U0->start_full_n(start_for_Softmax130_U0_full_n);
    AttentionMatmul_U0->start_out(AttentionMatmul_U0_start_out);
    AttentionMatmul_U0->start_write(AttentionMatmul_U0_start_write);
    AttentionMatmul_U0->in_r_TDATA(in_r_TDATA);
    AttentionMatmul_U0->in_r_TID(in_r_TID);
    AttentionMatmul_U0->in_r_TDEST(in_r_TDEST);
    AttentionMatmul_U0->in_r_TUSER(in_r_TUSER);
    AttentionMatmul_U0->in_r_TLAST(in_r_TLAST);
    AttentionMatmul_U0->out_V_data_V_din(AttentionMatmul_U0_out_V_data_V_din);
    AttentionMatmul_U0->out_V_data_V_full_n(pipe_1_V_data_V_full_n);
    AttentionMatmul_U0->out_V_data_V_write(AttentionMatmul_U0_out_V_data_V_write);
    AttentionMatmul_U0->out_V_id_V_din(AttentionMatmul_U0_out_V_id_V_din);
    AttentionMatmul_U0->out_V_id_V_full_n(pipe_1_V_id_V_full_n);
    AttentionMatmul_U0->out_V_id_V_write(AttentionMatmul_U0_out_V_id_V_write);
    AttentionMatmul_U0->out_V_dest_V_din(AttentionMatmul_U0_out_V_dest_V_din);
    AttentionMatmul_U0->out_V_dest_V_full_n(pipe_1_V_dest_V_full_n);
    AttentionMatmul_U0->out_V_dest_V_write(AttentionMatmul_U0_out_V_dest_V_write);
    AttentionMatmul_U0->out_V_user_V_din(AttentionMatmul_U0_out_V_user_V_din);
    AttentionMatmul_U0->out_V_user_V_full_n(pipe_1_V_user_V_full_n);
    AttentionMatmul_U0->out_V_user_V_write(AttentionMatmul_U0_out_V_user_V_write);
    AttentionMatmul_U0->out_V_last_V_din(AttentionMatmul_U0_out_V_last_V_din);
    AttentionMatmul_U0->out_V_last_V_full_n(pipe_1_V_last_V_full_n);
    AttentionMatmul_U0->out_V_last_V_write(AttentionMatmul_U0_out_V_last_V_write);
    AttentionMatmul_U0->ap_clk(ap_clk);
    AttentionMatmul_U0->ap_rst(ap_rst_n_inv);
    AttentionMatmul_U0->in_r_TVALID(in_r_TVALID);
    AttentionMatmul_U0->in_r_TREADY(AttentionMatmul_U0_in_r_TREADY);
    AttentionMatmul_U0->ap_done(AttentionMatmul_U0_ap_done);
    AttentionMatmul_U0->ap_ready(AttentionMatmul_U0_ap_ready);
    AttentionMatmul_U0->ap_idle(AttentionMatmul_U0_ap_idle);
    AttentionMatmul_U0->ap_continue(AttentionMatmul_U0_ap_continue);
    Softmax130_U0 = new Softmax130("Softmax130_U0");
    Softmax130_U0->in_V_data_V_dout(pipe_1_V_data_V_dout);
    Softmax130_U0->in_V_data_V_empty_n(pipe_1_V_data_V_empty_n);
    Softmax130_U0->in_V_data_V_read(Softmax130_U0_in_V_data_V_read);
    Softmax130_U0->in_V_id_V_dout(pipe_1_V_id_V_dout);
    Softmax130_U0->in_V_id_V_empty_n(pipe_1_V_id_V_empty_n);
    Softmax130_U0->in_V_id_V_read(Softmax130_U0_in_V_id_V_read);
    Softmax130_U0->in_V_dest_V_dout(pipe_1_V_dest_V_dout);
    Softmax130_U0->in_V_dest_V_empty_n(pipe_1_V_dest_V_empty_n);
    Softmax130_U0->in_V_dest_V_read(Softmax130_U0_in_V_dest_V_read);
    Softmax130_U0->in_V_user_V_dout(pipe_1_V_user_V_dout);
    Softmax130_U0->in_V_user_V_empty_n(pipe_1_V_user_V_empty_n);
    Softmax130_U0->in_V_user_V_read(Softmax130_U0_in_V_user_V_read);
    Softmax130_U0->in_V_last_V_dout(pipe_1_V_last_V_dout);
    Softmax130_U0->in_V_last_V_empty_n(pipe_1_V_last_V_empty_n);
    Softmax130_U0->in_V_last_V_read(Softmax130_U0_in_V_last_V_read);
    Softmax130_U0->out_r_TDATA(Softmax130_U0_out_r_TDATA);
    Softmax130_U0->out_r_TID(Softmax130_U0_out_r_TID);
    Softmax130_U0->out_r_TDEST(Softmax130_U0_out_r_TDEST);
    Softmax130_U0->out_r_TUSER(Softmax130_U0_out_r_TUSER);
    Softmax130_U0->out_r_TLAST(Softmax130_U0_out_r_TLAST);
    Softmax130_U0->ap_clk(ap_clk);
    Softmax130_U0->ap_rst(ap_rst_n_inv);
    Softmax130_U0->ap_start(Softmax130_U0_ap_start);
    Softmax130_U0->out_r_TVALID(Softmax130_U0_out_r_TVALID);
    Softmax130_U0->out_r_TREADY(out_r_TREADY);
    Softmax130_U0->ap_done(Softmax130_U0_ap_done);
    Softmax130_U0->ap_ready(Softmax130_U0_ap_ready);
    Softmax130_U0->ap_idle(Softmax130_U0_ap_idle);
    Softmax130_U0->ap_continue(Softmax130_U0_ap_continue);
    pipe_1_V_data_V_U = new fifo_w512_d2_A_x("pipe_1_V_data_V_U");
    pipe_1_V_data_V_U->clk(ap_clk);
    pipe_1_V_data_V_U->reset(ap_rst_n_inv);
    pipe_1_V_data_V_U->if_read_ce(ap_var_for_const0);
    pipe_1_V_data_V_U->if_write_ce(ap_var_for_const0);
    pipe_1_V_data_V_U->if_din(AttentionMatmul_U0_out_V_data_V_din);
    pipe_1_V_data_V_U->if_full_n(pipe_1_V_data_V_full_n);
    pipe_1_V_data_V_U->if_write(AttentionMatmul_U0_out_V_data_V_write);
    pipe_1_V_data_V_U->if_dout(pipe_1_V_data_V_dout);
    pipe_1_V_data_V_U->if_empty_n(pipe_1_V_data_V_empty_n);
    pipe_1_V_data_V_U->if_read(Softmax130_U0_in_V_data_V_read);
    pipe_1_V_id_V_U = new fifo_w8_d2_A_x("pipe_1_V_id_V_U");
    pipe_1_V_id_V_U->clk(ap_clk);
    pipe_1_V_id_V_U->reset(ap_rst_n_inv);
    pipe_1_V_id_V_U->if_read_ce(ap_var_for_const0);
    pipe_1_V_id_V_U->if_write_ce(ap_var_for_const0);
    pipe_1_V_id_V_U->if_din(AttentionMatmul_U0_out_V_id_V_din);
    pipe_1_V_id_V_U->if_full_n(pipe_1_V_id_V_full_n);
    pipe_1_V_id_V_U->if_write(AttentionMatmul_U0_out_V_id_V_write);
    pipe_1_V_id_V_U->if_dout(pipe_1_V_id_V_dout);
    pipe_1_V_id_V_U->if_empty_n(pipe_1_V_id_V_empty_n);
    pipe_1_V_id_V_U->if_read(Softmax130_U0_in_V_id_V_read);
    pipe_1_V_dest_V_U = new fifo_w8_d2_A_x("pipe_1_V_dest_V_U");
    pipe_1_V_dest_V_U->clk(ap_clk);
    pipe_1_V_dest_V_U->reset(ap_rst_n_inv);
    pipe_1_V_dest_V_U->if_read_ce(ap_var_for_const0);
    pipe_1_V_dest_V_U->if_write_ce(ap_var_for_const0);
    pipe_1_V_dest_V_U->if_din(AttentionMatmul_U0_out_V_dest_V_din);
    pipe_1_V_dest_V_U->if_full_n(pipe_1_V_dest_V_full_n);
    pipe_1_V_dest_V_U->if_write(AttentionMatmul_U0_out_V_dest_V_write);
    pipe_1_V_dest_V_U->if_dout(pipe_1_V_dest_V_dout);
    pipe_1_V_dest_V_U->if_empty_n(pipe_1_V_dest_V_empty_n);
    pipe_1_V_dest_V_U->if_read(Softmax130_U0_in_V_dest_V_read);
    pipe_1_V_user_V_U = new fifo_w16_d2_A_x0("pipe_1_V_user_V_U");
    pipe_1_V_user_V_U->clk(ap_clk);
    pipe_1_V_user_V_U->reset(ap_rst_n_inv);
    pipe_1_V_user_V_U->if_read_ce(ap_var_for_const0);
    pipe_1_V_user_V_U->if_write_ce(ap_var_for_const0);
    pipe_1_V_user_V_U->if_din(AttentionMatmul_U0_out_V_user_V_din);
    pipe_1_V_user_V_U->if_full_n(pipe_1_V_user_V_full_n);
    pipe_1_V_user_V_U->if_write(AttentionMatmul_U0_out_V_user_V_write);
    pipe_1_V_user_V_U->if_dout(pipe_1_V_user_V_dout);
    pipe_1_V_user_V_U->if_empty_n(pipe_1_V_user_V_empty_n);
    pipe_1_V_user_V_U->if_read(Softmax130_U0_in_V_user_V_read);
    pipe_1_V_last_V_U = new fifo_w1_d2_A_x("pipe_1_V_last_V_U");
    pipe_1_V_last_V_U->clk(ap_clk);
    pipe_1_V_last_V_U->reset(ap_rst_n_inv);
    pipe_1_V_last_V_U->if_read_ce(ap_var_for_const0);
    pipe_1_V_last_V_U->if_write_ce(ap_var_for_const0);
    pipe_1_V_last_V_U->if_din(AttentionMatmul_U0_out_V_last_V_din);
    pipe_1_V_last_V_U->if_full_n(pipe_1_V_last_V_full_n);
    pipe_1_V_last_V_U->if_write(AttentionMatmul_U0_out_V_last_V_write);
    pipe_1_V_last_V_U->if_dout(pipe_1_V_last_V_dout);
    pipe_1_V_last_V_U->if_empty_n(pipe_1_V_last_V_empty_n);
    pipe_1_V_last_V_U->if_read(Softmax130_U0_in_V_last_V_read);
    start_for_Softmax130_U0_U = new start_for_Softmax130_U0("start_for_Softmax130_U0_U");
    start_for_Softmax130_U0_U->clk(ap_clk);
    start_for_Softmax130_U0_U->reset(ap_rst_n_inv);
    start_for_Softmax130_U0_U->if_read_ce(ap_var_for_const0);
    start_for_Softmax130_U0_U->if_write_ce(ap_var_for_const0);
    start_for_Softmax130_U0_U->if_din(start_for_Softmax130_U0_din);
    start_for_Softmax130_U0_U->if_full_n(start_for_Softmax130_U0_full_n);
    start_for_Softmax130_U0_U->if_write(AttentionMatmul_U0_start_write);
    start_for_Softmax130_U0_U->if_dout(start_for_Softmax130_U0_dout);
    start_for_Softmax130_U0_U->if_empty_n(start_for_Softmax130_U0_empty_n);
    start_for_Softmax130_U0_U->if_read(Softmax130_U0_ap_ready);

    SC_METHOD(thread_AttentionMatmul_U0_ap_continue);

    SC_METHOD(thread_AttentionMatmul_U0_ap_start);

    SC_METHOD(thread_Softmax130_U0_ap_continue);

    SC_METHOD(thread_Softmax130_U0_ap_start);
    sensitive << ( start_for_Softmax130_U0_empty_n );

    SC_METHOD(thread_Softmax130_U0_start_full_n);

    SC_METHOD(thread_Softmax130_U0_start_write);

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_in_r_TREADY);
    sensitive << ( AttentionMatmul_U0_in_r_TREADY );

    SC_METHOD(thread_out_r_TDATA);
    sensitive << ( Softmax130_U0_out_r_TDATA );

    SC_METHOD(thread_out_r_TDEST);
    sensitive << ( Softmax130_U0_out_r_TDEST );

    SC_METHOD(thread_out_r_TID);
    sensitive << ( Softmax130_U0_out_r_TID );

    SC_METHOD(thread_out_r_TLAST);
    sensitive << ( Softmax130_U0_out_r_TLAST );

    SC_METHOD(thread_out_r_TUSER);
    sensitive << ( Softmax130_U0_out_r_TUSER );

    SC_METHOD(thread_out_r_TVALID);
    sensitive << ( Softmax130_U0_out_r_TVALID );

    SC_METHOD(thread_start_for_Softmax130_U0_din);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "kernel_4_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, in_r_TDATA, "(port)in_r_TDATA");
    sc_trace(mVcdFile, in_r_TID, "(port)in_r_TID");
    sc_trace(mVcdFile, in_r_TDEST, "(port)in_r_TDEST");
    sc_trace(mVcdFile, in_r_TUSER, "(port)in_r_TUSER");
    sc_trace(mVcdFile, in_r_TLAST, "(port)in_r_TLAST");
    sc_trace(mVcdFile, out_r_TDATA, "(port)out_r_TDATA");
    sc_trace(mVcdFile, out_r_TID, "(port)out_r_TID");
    sc_trace(mVcdFile, out_r_TDEST, "(port)out_r_TDEST");
    sc_trace(mVcdFile, out_r_TUSER, "(port)out_r_TUSER");
    sc_trace(mVcdFile, out_r_TLAST, "(port)out_r_TLAST");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, in_r_TVALID, "(port)in_r_TVALID");
    sc_trace(mVcdFile, in_r_TREADY, "(port)in_r_TREADY");
    sc_trace(mVcdFile, out_r_TVALID, "(port)out_r_TVALID");
    sc_trace(mVcdFile, out_r_TREADY, "(port)out_r_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, AttentionMatmul_U0_ap_start, "AttentionMatmul_U0_ap_start");
    sc_trace(mVcdFile, AttentionMatmul_U0_start_out, "AttentionMatmul_U0_start_out");
    sc_trace(mVcdFile, AttentionMatmul_U0_start_write, "AttentionMatmul_U0_start_write");
    sc_trace(mVcdFile, AttentionMatmul_U0_out_V_data_V_din, "AttentionMatmul_U0_out_V_data_V_din");
    sc_trace(mVcdFile, AttentionMatmul_U0_out_V_data_V_write, "AttentionMatmul_U0_out_V_data_V_write");
    sc_trace(mVcdFile, AttentionMatmul_U0_out_V_id_V_din, "AttentionMatmul_U0_out_V_id_V_din");
    sc_trace(mVcdFile, AttentionMatmul_U0_out_V_id_V_write, "AttentionMatmul_U0_out_V_id_V_write");
    sc_trace(mVcdFile, AttentionMatmul_U0_out_V_dest_V_din, "AttentionMatmul_U0_out_V_dest_V_din");
    sc_trace(mVcdFile, AttentionMatmul_U0_out_V_dest_V_write, "AttentionMatmul_U0_out_V_dest_V_write");
    sc_trace(mVcdFile, AttentionMatmul_U0_out_V_user_V_din, "AttentionMatmul_U0_out_V_user_V_din");
    sc_trace(mVcdFile, AttentionMatmul_U0_out_V_user_V_write, "AttentionMatmul_U0_out_V_user_V_write");
    sc_trace(mVcdFile, AttentionMatmul_U0_out_V_last_V_din, "AttentionMatmul_U0_out_V_last_V_din");
    sc_trace(mVcdFile, AttentionMatmul_U0_out_V_last_V_write, "AttentionMatmul_U0_out_V_last_V_write");
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, AttentionMatmul_U0_in_r_TREADY, "AttentionMatmul_U0_in_r_TREADY");
    sc_trace(mVcdFile, AttentionMatmul_U0_ap_done, "AttentionMatmul_U0_ap_done");
    sc_trace(mVcdFile, AttentionMatmul_U0_ap_ready, "AttentionMatmul_U0_ap_ready");
    sc_trace(mVcdFile, AttentionMatmul_U0_ap_idle, "AttentionMatmul_U0_ap_idle");
    sc_trace(mVcdFile, AttentionMatmul_U0_ap_continue, "AttentionMatmul_U0_ap_continue");
    sc_trace(mVcdFile, Softmax130_U0_in_V_data_V_read, "Softmax130_U0_in_V_data_V_read");
    sc_trace(mVcdFile, Softmax130_U0_in_V_id_V_read, "Softmax130_U0_in_V_id_V_read");
    sc_trace(mVcdFile, Softmax130_U0_in_V_dest_V_read, "Softmax130_U0_in_V_dest_V_read");
    sc_trace(mVcdFile, Softmax130_U0_in_V_user_V_read, "Softmax130_U0_in_V_user_V_read");
    sc_trace(mVcdFile, Softmax130_U0_in_V_last_V_read, "Softmax130_U0_in_V_last_V_read");
    sc_trace(mVcdFile, Softmax130_U0_out_r_TDATA, "Softmax130_U0_out_r_TDATA");
    sc_trace(mVcdFile, Softmax130_U0_out_r_TID, "Softmax130_U0_out_r_TID");
    sc_trace(mVcdFile, Softmax130_U0_out_r_TDEST, "Softmax130_U0_out_r_TDEST");
    sc_trace(mVcdFile, Softmax130_U0_out_r_TUSER, "Softmax130_U0_out_r_TUSER");
    sc_trace(mVcdFile, Softmax130_U0_out_r_TLAST, "Softmax130_U0_out_r_TLAST");
    sc_trace(mVcdFile, Softmax130_U0_ap_start, "Softmax130_U0_ap_start");
    sc_trace(mVcdFile, Softmax130_U0_out_r_TVALID, "Softmax130_U0_out_r_TVALID");
    sc_trace(mVcdFile, Softmax130_U0_ap_done, "Softmax130_U0_ap_done");
    sc_trace(mVcdFile, Softmax130_U0_ap_ready, "Softmax130_U0_ap_ready");
    sc_trace(mVcdFile, Softmax130_U0_ap_idle, "Softmax130_U0_ap_idle");
    sc_trace(mVcdFile, Softmax130_U0_ap_continue, "Softmax130_U0_ap_continue");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, pipe_1_V_data_V_full_n, "pipe_1_V_data_V_full_n");
    sc_trace(mVcdFile, pipe_1_V_data_V_dout, "pipe_1_V_data_V_dout");
    sc_trace(mVcdFile, pipe_1_V_data_V_empty_n, "pipe_1_V_data_V_empty_n");
    sc_trace(mVcdFile, pipe_1_V_id_V_full_n, "pipe_1_V_id_V_full_n");
    sc_trace(mVcdFile, pipe_1_V_id_V_dout, "pipe_1_V_id_V_dout");
    sc_trace(mVcdFile, pipe_1_V_id_V_empty_n, "pipe_1_V_id_V_empty_n");
    sc_trace(mVcdFile, pipe_1_V_dest_V_full_n, "pipe_1_V_dest_V_full_n");
    sc_trace(mVcdFile, pipe_1_V_dest_V_dout, "pipe_1_V_dest_V_dout");
    sc_trace(mVcdFile, pipe_1_V_dest_V_empty_n, "pipe_1_V_dest_V_empty_n");
    sc_trace(mVcdFile, pipe_1_V_user_V_full_n, "pipe_1_V_user_V_full_n");
    sc_trace(mVcdFile, pipe_1_V_user_V_dout, "pipe_1_V_user_V_dout");
    sc_trace(mVcdFile, pipe_1_V_user_V_empty_n, "pipe_1_V_user_V_empty_n");
    sc_trace(mVcdFile, pipe_1_V_last_V_full_n, "pipe_1_V_last_V_full_n");
    sc_trace(mVcdFile, pipe_1_V_last_V_dout, "pipe_1_V_last_V_dout");
    sc_trace(mVcdFile, pipe_1_V_last_V_empty_n, "pipe_1_V_last_V_empty_n");
    sc_trace(mVcdFile, start_for_Softmax130_U0_din, "start_for_Softmax130_U0_din");
    sc_trace(mVcdFile, start_for_Softmax130_U0_full_n, "start_for_Softmax130_U0_full_n");
    sc_trace(mVcdFile, start_for_Softmax130_U0_dout, "start_for_Softmax130_U0_dout");
    sc_trace(mVcdFile, start_for_Softmax130_U0_empty_n, "start_for_Softmax130_U0_empty_n");
    sc_trace(mVcdFile, Softmax130_U0_start_full_n, "Softmax130_U0_start_full_n");
    sc_trace(mVcdFile, Softmax130_U0_start_write, "Softmax130_U0_start_write");
#endif

    }
    mHdltvinHandle.open("kernel_4.hdltvin.dat");
    mHdltvoutHandle.open("kernel_4.hdltvout.dat");
}

kernel_4::~kernel_4() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete AttentionMatmul_U0;
    delete Softmax130_U0;
    delete pipe_1_V_data_V_U;
    delete pipe_1_V_id_V_U;
    delete pipe_1_V_dest_V_U;
    delete pipe_1_V_user_V_U;
    delete pipe_1_V_last_V_U;
    delete start_for_Softmax130_U0_U;
}

void kernel_4::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void kernel_4::thread_AttentionMatmul_U0_ap_continue() {
    AttentionMatmul_U0_ap_continue = ap_const_logic_1;
}

void kernel_4::thread_AttentionMatmul_U0_ap_start() {
    AttentionMatmul_U0_ap_start = ap_const_logic_1;
}

void kernel_4::thread_Softmax130_U0_ap_continue() {
    Softmax130_U0_ap_continue = ap_const_logic_1;
}

void kernel_4::thread_Softmax130_U0_ap_start() {
    Softmax130_U0_ap_start = start_for_Softmax130_U0_empty_n.read();
}

void kernel_4::thread_Softmax130_U0_start_full_n() {
    Softmax130_U0_start_full_n = ap_const_logic_1;
}

void kernel_4::thread_Softmax130_U0_start_write() {
    Softmax130_U0_start_write = ap_const_logic_0;
}

void kernel_4::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void kernel_4::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_0;
}

void kernel_4::thread_in_r_TREADY() {
    in_r_TREADY = AttentionMatmul_U0_in_r_TREADY.read();
}

void kernel_4::thread_out_r_TDATA() {
    out_r_TDATA = Softmax130_U0_out_r_TDATA.read();
}

void kernel_4::thread_out_r_TDEST() {
    out_r_TDEST = Softmax130_U0_out_r_TDEST.read();
}

void kernel_4::thread_out_r_TID() {
    out_r_TID = Softmax130_U0_out_r_TID.read();
}

void kernel_4::thread_out_r_TLAST() {
    out_r_TLAST = Softmax130_U0_out_r_TLAST.read();
}

void kernel_4::thread_out_r_TUSER() {
    out_r_TUSER = Softmax130_U0_out_r_TUSER.read();
}

void kernel_4::thread_out_r_TVALID() {
    out_r_TVALID = Softmax130_U0_out_r_TVALID.read();
}

void kernel_4::thread_start_for_Softmax130_U0_din() {
    start_for_Softmax130_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void kernel_4::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"in_r_TDATA\" :  \"" << in_r_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_r_TID\" :  \"" << in_r_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_r_TDEST\" :  \"" << in_r_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_r_TUSER\" :  \"" << in_r_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_r_TLAST\" :  \"" << in_r_TLAST.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"out_r_TDATA\" :  \"" << out_r_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_TID\" :  \"" << out_r_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_TDEST\" :  \"" << out_r_TDEST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_TUSER\" :  \"" << out_r_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_TLAST\" :  \"" << out_r_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_r_TVALID\" :  \"" << in_r_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_r_TREADY\" :  \"" << in_r_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_TVALID\" :  \"" << out_r_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"out_r_TREADY\" :  \"" << out_r_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

