// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Softmax130_HH_
#define _Softmax130_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "softmax_save_data131.h"
#include "softmax_process_1132.h"
#include "softmax_QuantAct_1_c.h"
#include "softmax_process_2134.h"
#include "softmax_write_out135.h"
#include "fifo_w96_d2_A.h"
#include "fifo_w32_d2_A_x.h"
#include "fifo_w64_d2_A.h"
#include "fifo_w128_d2_A.h"
#include "fifo_w16_d2_A_x.h"
#include "start_for_softmax_process_1132_U0.h"
#include "start_for_softmax_write_out135_U0.h"
#include "start_for_softmax_QuantAct_1_c_U0.h"
#include "start_for_softmax_process_2134_U0.h"

namespace ap_rtl {

struct Softmax130 : public sc_module {
    // Port declarations 29
    sc_in< sc_lv<512> > in_V_data_V_dout;
    sc_in< sc_logic > in_V_data_V_empty_n;
    sc_out< sc_logic > in_V_data_V_read;
    sc_in< sc_lv<8> > in_V_id_V_dout;
    sc_in< sc_logic > in_V_id_V_empty_n;
    sc_out< sc_logic > in_V_id_V_read;
    sc_in< sc_lv<8> > in_V_dest_V_dout;
    sc_in< sc_logic > in_V_dest_V_empty_n;
    sc_out< sc_logic > in_V_dest_V_read;
    sc_in< sc_lv<16> > in_V_user_V_dout;
    sc_in< sc_logic > in_V_user_V_empty_n;
    sc_out< sc_logic > in_V_user_V_read;
    sc_in< sc_lv<1> > in_V_last_V_dout;
    sc_in< sc_logic > in_V_last_V_empty_n;
    sc_out< sc_logic > in_V_last_V_read;
    sc_out< sc_lv<512> > out_r_TDATA;
    sc_out< sc_lv<8> > out_r_TID;
    sc_out< sc_lv<8> > out_r_TDEST;
    sc_out< sc_lv<16> > out_r_TUSER;
    sc_out< sc_lv<1> > out_r_TLAST;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > out_r_TVALID;
    sc_in< sc_logic > out_r_TREADY;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > ap_idle;
    sc_in< sc_logic > ap_continue;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    Softmax130(sc_module_name name);
    SC_HAS_PROCESS(Softmax130);

    ~Softmax130();

    sc_trace_file* mVcdFile;

    softmax_save_data131* softmax_save_data131_U0;
    softmax_process_1132* softmax_process_1132_U0;
    softmax_QuantAct_1_c* softmax_QuantAct_1_c_U0;
    softmax_process_2134* softmax_process_2134_U0;
    softmax_write_out135* softmax_write_out135_U0;
    fifo_w96_d2_A* in_write_n_V_V_U;
    fifo_w32_d2_A_x* in_proc_1_iter_r_V_V_U;
    fifo_w32_d2_A_x* in_proc_1_iter_c_V_V_U;
    fifo_w64_d2_A* in_proc_1_V_V_U;
    fifo_w32_d2_A_x* in_quant_iter_r_V_V_U;
    fifo_w32_d2_A_x* in_quant_iter_c_V_V_U;
    fifo_w128_d2_A* in_quant_V_V_U;
    fifo_w32_d2_A_x* in_proc_2_iter_r_V_V_U;
    fifo_w32_d2_A_x* in_proc_2_iter_c_V_V_U;
    fifo_w32_d2_A_x* in_proc_2_V_V_U;
    fifo_w32_d2_A_x* in_write_2_iter_c_V_s_U;
    fifo_w16_d2_A_x* in_write_V_V_U;
    start_for_softmax_process_1132_U0* start_for_softmax_process_1132_U0_U;
    start_for_softmax_write_out135_U0* start_for_softmax_write_out135_U0_U;
    start_for_softmax_QuantAct_1_c_U0* start_for_softmax_QuantAct_1_c_U0_U;
    start_for_softmax_process_2134_U0* start_for_softmax_process_2134_U0_U;
    sc_signal< sc_logic > softmax_save_data131_U0_ap_start;
    sc_signal< sc_logic > softmax_save_data131_U0_start_full_n;
    sc_signal< sc_logic > softmax_save_data131_U0_ap_done;
    sc_signal< sc_logic > softmax_save_data131_U0_ap_continue;
    sc_signal< sc_logic > softmax_save_data131_U0_ap_idle;
    sc_signal< sc_logic > softmax_save_data131_U0_ap_ready;
    sc_signal< sc_logic > softmax_save_data131_U0_start_out;
    sc_signal< sc_logic > softmax_save_data131_U0_start_write;
    sc_signal< sc_logic > softmax_save_data131_U0_in_V_data_V_read;
    sc_signal< sc_logic > softmax_save_data131_U0_in_V_id_V_read;
    sc_signal< sc_logic > softmax_save_data131_U0_in_V_dest_V_read;
    sc_signal< sc_logic > softmax_save_data131_U0_in_V_user_V_read;
    sc_signal< sc_logic > softmax_save_data131_U0_in_V_last_V_read;
    sc_signal< sc_lv<96> > softmax_save_data131_U0_out_n_V_V_din;
    sc_signal< sc_logic > softmax_save_data131_U0_out_n_V_V_write;
    sc_signal< sc_lv<32> > softmax_save_data131_U0_out_iter_r_V_V_din;
    sc_signal< sc_logic > softmax_save_data131_U0_out_iter_r_V_V_write;
    sc_signal< sc_lv<32> > softmax_save_data131_U0_out_iter_c_V_V_din;
    sc_signal< sc_logic > softmax_save_data131_U0_out_iter_c_V_V_write;
    sc_signal< sc_lv<64> > softmax_save_data131_U0_out_V_V_din;
    sc_signal< sc_logic > softmax_save_data131_U0_out_V_V_write;
    sc_signal< sc_logic > softmax_process_1132_U0_ap_start;
    sc_signal< sc_logic > softmax_process_1132_U0_ap_done;
    sc_signal< sc_logic > softmax_process_1132_U0_ap_continue;
    sc_signal< sc_logic > softmax_process_1132_U0_ap_idle;
    sc_signal< sc_logic > softmax_process_1132_U0_ap_ready;
    sc_signal< sc_logic > softmax_process_1132_U0_start_out;
    sc_signal< sc_logic > softmax_process_1132_U0_start_write;
    sc_signal< sc_logic > softmax_process_1132_U0_in_iter_r_V_V_read;
    sc_signal< sc_logic > softmax_process_1132_U0_in_iter_c_V_V_read;
    sc_signal< sc_logic > softmax_process_1132_U0_in_V_V_read;
    sc_signal< sc_lv<32> > softmax_process_1132_U0_out_iter_r_V_V_din;
    sc_signal< sc_logic > softmax_process_1132_U0_out_iter_r_V_V_write;
    sc_signal< sc_lv<32> > softmax_process_1132_U0_out_iter_c_V_V_din;
    sc_signal< sc_logic > softmax_process_1132_U0_out_iter_c_V_V_write;
    sc_signal< sc_lv<128> > softmax_process_1132_U0_out_V_V_din;
    sc_signal< sc_logic > softmax_process_1132_U0_out_V_V_write;
    sc_signal< sc_logic > softmax_QuantAct_1_c_U0_ap_start;
    sc_signal< sc_logic > softmax_QuantAct_1_c_U0_ap_done;
    sc_signal< sc_logic > softmax_QuantAct_1_c_U0_ap_continue;
    sc_signal< sc_logic > softmax_QuantAct_1_c_U0_ap_idle;
    sc_signal< sc_logic > softmax_QuantAct_1_c_U0_ap_ready;
    sc_signal< sc_logic > softmax_QuantAct_1_c_U0_start_out;
    sc_signal< sc_logic > softmax_QuantAct_1_c_U0_start_write;
    sc_signal< sc_logic > softmax_QuantAct_1_c_U0_in_iter_r_V_V_read;
    sc_signal< sc_logic > softmax_QuantAct_1_c_U0_in_iter_c_V_V_read;
    sc_signal< sc_logic > softmax_QuantAct_1_c_U0_in_V_V_read;
    sc_signal< sc_lv<32> > softmax_QuantAct_1_c_U0_out_iter_r_V_V_din;
    sc_signal< sc_logic > softmax_QuantAct_1_c_U0_out_iter_r_V_V_write;
    sc_signal< sc_lv<32> > softmax_QuantAct_1_c_U0_out_iter_c_V_V_din;
    sc_signal< sc_logic > softmax_QuantAct_1_c_U0_out_iter_c_V_V_write;
    sc_signal< sc_lv<32> > softmax_QuantAct_1_c_U0_out_V_V_din;
    sc_signal< sc_logic > softmax_QuantAct_1_c_U0_out_V_V_write;
    sc_signal< sc_logic > softmax_process_2134_U0_ap_start;
    sc_signal< sc_logic > softmax_process_2134_U0_ap_done;
    sc_signal< sc_logic > softmax_process_2134_U0_ap_continue;
    sc_signal< sc_logic > softmax_process_2134_U0_ap_idle;
    sc_signal< sc_logic > softmax_process_2134_U0_ap_ready;
    sc_signal< sc_logic > softmax_process_2134_U0_in_iter_r_V_V_read;
    sc_signal< sc_logic > softmax_process_2134_U0_in_iter_c_V_V_read;
    sc_signal< sc_logic > softmax_process_2134_U0_in_V_V_read;
    sc_signal< sc_lv<32> > softmax_process_2134_U0_out_iter_c_V_V_din;
    sc_signal< sc_logic > softmax_process_2134_U0_out_iter_c_V_V_write;
    sc_signal< sc_lv<16> > softmax_process_2134_U0_out_V_V_din;
    sc_signal< sc_logic > softmax_process_2134_U0_out_V_V_write;
    sc_signal< sc_logic > softmax_write_out135_U0_ap_start;
    sc_signal< sc_logic > softmax_write_out135_U0_ap_done;
    sc_signal< sc_logic > softmax_write_out135_U0_ap_continue;
    sc_signal< sc_logic > softmax_write_out135_U0_ap_idle;
    sc_signal< sc_logic > softmax_write_out135_U0_ap_ready;
    sc_signal< sc_logic > softmax_write_out135_U0_in_n_V_V_read;
    sc_signal< sc_logic > softmax_write_out135_U0_in_iter_c_V_V_read;
    sc_signal< sc_logic > softmax_write_out135_U0_in_V_V_read;
    sc_signal< sc_lv<512> > softmax_write_out135_U0_out_r_TDATA;
    sc_signal< sc_logic > softmax_write_out135_U0_out_r_TVALID;
    sc_signal< sc_lv<8> > softmax_write_out135_U0_out_r_TID;
    sc_signal< sc_lv<8> > softmax_write_out135_U0_out_r_TDEST;
    sc_signal< sc_lv<16> > softmax_write_out135_U0_out_r_TUSER;
    sc_signal< sc_lv<1> > softmax_write_out135_U0_out_r_TLAST;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > in_write_n_V_V_full_n;
    sc_signal< sc_lv<96> > in_write_n_V_V_dout;
    sc_signal< sc_logic > in_write_n_V_V_empty_n;
    sc_signal< sc_logic > in_proc_1_iter_r_V_V_full_n;
    sc_signal< sc_lv<32> > in_proc_1_iter_r_V_V_dout;
    sc_signal< sc_logic > in_proc_1_iter_r_V_V_empty_n;
    sc_signal< sc_logic > in_proc_1_iter_c_V_V_full_n;
    sc_signal< sc_lv<32> > in_proc_1_iter_c_V_V_dout;
    sc_signal< sc_logic > in_proc_1_iter_c_V_V_empty_n;
    sc_signal< sc_logic > in_proc_1_V_V_full_n;
    sc_signal< sc_lv<64> > in_proc_1_V_V_dout;
    sc_signal< sc_logic > in_proc_1_V_V_empty_n;
    sc_signal< sc_logic > in_quant_iter_r_V_V_full_n;
    sc_signal< sc_lv<32> > in_quant_iter_r_V_V_dout;
    sc_signal< sc_logic > in_quant_iter_r_V_V_empty_n;
    sc_signal< sc_logic > in_quant_iter_c_V_V_full_n;
    sc_signal< sc_lv<32> > in_quant_iter_c_V_V_dout;
    sc_signal< sc_logic > in_quant_iter_c_V_V_empty_n;
    sc_signal< sc_logic > in_quant_V_V_full_n;
    sc_signal< sc_lv<128> > in_quant_V_V_dout;
    sc_signal< sc_logic > in_quant_V_V_empty_n;
    sc_signal< sc_logic > in_proc_2_iter_r_V_V_full_n;
    sc_signal< sc_lv<32> > in_proc_2_iter_r_V_V_dout;
    sc_signal< sc_logic > in_proc_2_iter_r_V_V_empty_n;
    sc_signal< sc_logic > in_proc_2_iter_c_V_V_full_n;
    sc_signal< sc_lv<32> > in_proc_2_iter_c_V_V_dout;
    sc_signal< sc_logic > in_proc_2_iter_c_V_V_empty_n;
    sc_signal< sc_logic > in_proc_2_V_V_full_n;
    sc_signal< sc_lv<32> > in_proc_2_V_V_dout;
    sc_signal< sc_logic > in_proc_2_V_V_empty_n;
    sc_signal< sc_logic > in_write_2_iter_c_V_s_full_n;
    sc_signal< sc_lv<32> > in_write_2_iter_c_V_s_dout;
    sc_signal< sc_logic > in_write_2_iter_c_V_s_empty_n;
    sc_signal< sc_logic > in_write_V_V_full_n;
    sc_signal< sc_lv<16> > in_write_V_V_dout;
    sc_signal< sc_logic > in_write_V_V_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_lv<1> > start_for_softmax_process_1132_U0_din;
    sc_signal< sc_logic > start_for_softmax_process_1132_U0_full_n;
    sc_signal< sc_lv<1> > start_for_softmax_process_1132_U0_dout;
    sc_signal< sc_logic > start_for_softmax_process_1132_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_softmax_write_out135_U0_din;
    sc_signal< sc_logic > start_for_softmax_write_out135_U0_full_n;
    sc_signal< sc_lv<1> > start_for_softmax_write_out135_U0_dout;
    sc_signal< sc_logic > start_for_softmax_write_out135_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_softmax_QuantAct_1_c_U0_din;
    sc_signal< sc_logic > start_for_softmax_QuantAct_1_c_U0_full_n;
    sc_signal< sc_lv<1> > start_for_softmax_QuantAct_1_c_U0_dout;
    sc_signal< sc_logic > start_for_softmax_QuantAct_1_c_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_softmax_process_2134_U0_din;
    sc_signal< sc_logic > start_for_softmax_process_2134_U0_full_n;
    sc_signal< sc_lv<1> > start_for_softmax_process_2134_U0_dout;
    sc_signal< sc_logic > start_for_softmax_process_2134_U0_empty_n;
    sc_signal< sc_logic > softmax_process_2134_U0_start_full_n;
    sc_signal< sc_logic > softmax_process_2134_U0_start_write;
    sc_signal< sc_logic > softmax_write_out135_U0_start_full_n;
    sc_signal< sc_logic > softmax_write_out135_U0_start_write;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<512> ap_const_lv512_lc_1;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_logic ap_const_logic_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_in_V_data_V_read();
    void thread_in_V_dest_V_read();
    void thread_in_V_id_V_read();
    void thread_in_V_last_V_read();
    void thread_in_V_user_V_read();
    void thread_out_r_TDATA();
    void thread_out_r_TDEST();
    void thread_out_r_TID();
    void thread_out_r_TLAST();
    void thread_out_r_TUSER();
    void thread_out_r_TVALID();
    void thread_softmax_QuantAct_1_c_U0_ap_continue();
    void thread_softmax_QuantAct_1_c_U0_ap_start();
    void thread_softmax_process_1132_U0_ap_continue();
    void thread_softmax_process_1132_U0_ap_start();
    void thread_softmax_process_2134_U0_ap_continue();
    void thread_softmax_process_2134_U0_ap_start();
    void thread_softmax_process_2134_U0_start_full_n();
    void thread_softmax_process_2134_U0_start_write();
    void thread_softmax_save_data131_U0_ap_continue();
    void thread_softmax_save_data131_U0_ap_start();
    void thread_softmax_save_data131_U0_start_full_n();
    void thread_softmax_write_out135_U0_ap_continue();
    void thread_softmax_write_out135_U0_ap_start();
    void thread_softmax_write_out135_U0_start_full_n();
    void thread_softmax_write_out135_U0_start_write();
    void thread_start_for_softmax_QuantAct_1_c_U0_din();
    void thread_start_for_softmax_process_1132_U0_din();
    void thread_start_for_softmax_process_2134_U0_din();
    void thread_start_for_softmax_write_out135_U0_din();
};

}

using namespace ap_rtl;

#endif
