// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module layernorm_compute_va (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        n_pipe1_V_V_dout,
        n_pipe1_V_V_empty_n,
        n_pipe1_V_V_read,
        n_pipe2_V_V_din,
        n_pipe2_V_V_full_n,
        n_pipe2_V_V_write,
        mean_pipe1_V_V_dout,
        mean_pipe1_V_V_empty_n,
        mean_pipe1_V_V_read,
        in_compute_V_V_0_dout,
        in_compute_V_V_0_empty_n,
        in_compute_V_V_0_read,
        in_compute_V_V_1_dout,
        in_compute_V_V_1_empty_n,
        in_compute_V_V_1_read,
        in_compute_V_V_2_dout,
        in_compute_V_V_2_empty_n,
        in_compute_V_V_2_read,
        in_compute_V_V_3_dout,
        in_compute_V_V_3_empty_n,
        in_compute_V_V_3_read,
        in_compute_V_V_4_dout,
        in_compute_V_V_4_empty_n,
        in_compute_V_V_4_read,
        in_compute_V_V_5_dout,
        in_compute_V_V_5_empty_n,
        in_compute_V_V_5_read,
        in_compute_V_V_6_dout,
        in_compute_V_V_6_empty_n,
        in_compute_V_V_6_read,
        in_compute_V_V_7_dout,
        in_compute_V_V_7_empty_n,
        in_compute_V_V_7_read,
        in_compute_V_V_8_dout,
        in_compute_V_V_8_empty_n,
        in_compute_V_V_8_read,
        in_compute_V_V_9_dout,
        in_compute_V_V_9_empty_n,
        in_compute_V_V_9_read,
        in_compute_V_V_10_dout,
        in_compute_V_V_10_empty_n,
        in_compute_V_V_10_read,
        in_compute_V_V_11_dout,
        in_compute_V_V_11_empty_n,
        in_compute_V_V_11_read,
        in_compute_V_V_12_dout,
        in_compute_V_V_12_empty_n,
        in_compute_V_V_12_read,
        in_compute_V_V_13_dout,
        in_compute_V_V_13_empty_n,
        in_compute_V_V_13_read,
        in_compute_V_V_14_dout,
        in_compute_V_V_14_empty_n,
        in_compute_V_V_14_read,
        in_compute_V_V_15_dout,
        in_compute_V_V_15_empty_n,
        in_compute_V_V_15_read,
        in_sqrt_V_V_din,
        in_sqrt_V_V_full_n,
        in_sqrt_V_V_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state7 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] n_pipe1_V_V_dout;
input   n_pipe1_V_V_empty_n;
output   n_pipe1_V_V_read;
output  [31:0] n_pipe2_V_V_din;
input   n_pipe2_V_V_full_n;
output   n_pipe2_V_V_write;
input  [31:0] mean_pipe1_V_V_dout;
input   mean_pipe1_V_V_empty_n;
output   mean_pipe1_V_V_read;
input  [31:0] in_compute_V_V_0_dout;
input   in_compute_V_V_0_empty_n;
output   in_compute_V_V_0_read;
input  [31:0] in_compute_V_V_1_dout;
input   in_compute_V_V_1_empty_n;
output   in_compute_V_V_1_read;
input  [31:0] in_compute_V_V_2_dout;
input   in_compute_V_V_2_empty_n;
output   in_compute_V_V_2_read;
input  [31:0] in_compute_V_V_3_dout;
input   in_compute_V_V_3_empty_n;
output   in_compute_V_V_3_read;
input  [31:0] in_compute_V_V_4_dout;
input   in_compute_V_V_4_empty_n;
output   in_compute_V_V_4_read;
input  [31:0] in_compute_V_V_5_dout;
input   in_compute_V_V_5_empty_n;
output   in_compute_V_V_5_read;
input  [31:0] in_compute_V_V_6_dout;
input   in_compute_V_V_6_empty_n;
output   in_compute_V_V_6_read;
input  [31:0] in_compute_V_V_7_dout;
input   in_compute_V_V_7_empty_n;
output   in_compute_V_V_7_read;
input  [31:0] in_compute_V_V_8_dout;
input   in_compute_V_V_8_empty_n;
output   in_compute_V_V_8_read;
input  [31:0] in_compute_V_V_9_dout;
input   in_compute_V_V_9_empty_n;
output   in_compute_V_V_9_read;
input  [31:0] in_compute_V_V_10_dout;
input   in_compute_V_V_10_empty_n;
output   in_compute_V_V_10_read;
input  [31:0] in_compute_V_V_11_dout;
input   in_compute_V_V_11_empty_n;
output   in_compute_V_V_11_read;
input  [31:0] in_compute_V_V_12_dout;
input   in_compute_V_V_12_empty_n;
output   in_compute_V_V_12_read;
input  [31:0] in_compute_V_V_13_dout;
input   in_compute_V_V_13_empty_n;
output   in_compute_V_V_13_read;
input  [31:0] in_compute_V_V_14_dout;
input   in_compute_V_V_14_empty_n;
output   in_compute_V_V_14_read;
input  [31:0] in_compute_V_V_15_dout;
input   in_compute_V_V_15_empty_n;
output   in_compute_V_V_15_read;
output  [31:0] in_sqrt_V_V_din;
input   in_sqrt_V_V_full_n;
output   in_sqrt_V_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg n_pipe1_V_V_read;
reg n_pipe2_V_V_write;
reg mean_pipe1_V_V_read;
reg in_compute_V_V_0_read;
reg in_compute_V_V_1_read;
reg in_compute_V_V_2_read;
reg in_compute_V_V_3_read;
reg in_compute_V_V_4_read;
reg in_compute_V_V_5_read;
reg in_compute_V_V_6_read;
reg in_compute_V_V_7_read;
reg in_compute_V_V_8_read;
reg in_compute_V_V_9_read;
reg in_compute_V_V_10_read;
reg in_compute_V_V_11_read;
reg in_compute_V_V_12_read;
reg in_compute_V_V_13_read;
reg in_compute_V_V_14_read;
reg in_compute_V_V_15_read;
reg in_sqrt_V_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    n_pipe1_V_V_blk_n;
reg    n_pipe2_V_V_blk_n;
reg    mean_pipe1_V_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond_flatten_reg_1545;
reg   [0:0] tmp_18_i_reg_1554;
reg    in_compute_V_V_0_blk_n;
reg    in_compute_V_V_1_blk_n;
reg    in_compute_V_V_2_blk_n;
reg    in_compute_V_V_3_blk_n;
reg    in_compute_V_V_4_blk_n;
reg    in_compute_V_V_5_blk_n;
reg    in_compute_V_V_6_blk_n;
reg    in_compute_V_V_7_blk_n;
reg    in_compute_V_V_8_blk_n;
reg    in_compute_V_V_9_blk_n;
reg    in_compute_V_V_10_blk_n;
reg    in_compute_V_V_11_blk_n;
reg    in_compute_V_V_12_blk_n;
reg    in_compute_V_V_13_blk_n;
reg    in_compute_V_V_14_blk_n;
reg    in_compute_V_V_15_blk_n;
reg    in_sqrt_V_V_blk_n;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] exitcond_flatten_reg_1545_pp0_iter3_reg;
reg   [0:0] tmp_19_i_reg_1558;
reg   [0:0] tmp_19_i_reg_1558_pp0_iter3_reg;
reg   [37:0] indvar_flatten_reg_467;
reg   [5:0] l_i_reg_478;
reg   [31:0] var_V_0_1_i_reg_489;
reg   [31:0] var_V_1_1_i_reg_500;
reg   [31:0] var_V_2_1_i_reg_511;
reg   [31:0] var_V_3_1_i_reg_522;
reg   [31:0] var_V_4_1_i_reg_533;
reg   [31:0] var_V_5_1_i_reg_544;
reg   [31:0] var_V_6_1_i_reg_555;
reg   [31:0] var_V_7_1_i_reg_566;
reg   [31:0] var_V_8_1_i_reg_577;
reg   [31:0] var_V_9_1_i_reg_588;
reg   [31:0] var_V_10_1_i_reg_599;
reg   [31:0] var_V_11_1_i_reg_610;
reg   [31:0] var_V_12_1_i_reg_621;
reg   [31:0] var_V_13_1_i_reg_632;
reg   [31:0] var_V_14_1_i_reg_643;
reg   [31:0] var_V_15_1_i_reg_654;
reg   [31:0] p_0111_1_i_reg_665;
wire   [37:0] bound_fu_913_p2;
reg   [37:0] bound_reg_1540;
reg    ap_block_state1;
wire   [0:0] exitcond_flatten_fu_919_p2;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_predicate_op45_read_state3;
reg    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
reg    ap_predicate_op201_write_state6;
reg    ap_block_state6_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond_flatten_reg_1545_pp0_iter1_reg;
reg   [0:0] exitcond_flatten_reg_1545_pp0_iter2_reg;
wire   [37:0] indvar_flatten_next_fu_924_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] tmp_18_i_fu_944_p2;
reg   [0:0] tmp_18_i_reg_1554_pp0_iter1_reg;
reg   [0:0] tmp_18_i_reg_1554_pp0_iter2_reg;
wire   [0:0] tmp_19_i_fu_950_p2;
reg   [0:0] tmp_19_i_reg_1558_pp0_iter1_reg;
reg   [0:0] tmp_19_i_reg_1558_pp0_iter2_reg;
wire   [5:0] l_fu_956_p2;
reg   [31:0] tmp_V_93_reg_1567;
reg   [31:0] tmp_V_94_reg_1572;
reg   [31:0] tmp_V_95_reg_1577;
reg   [31:0] tmp_V_96_reg_1582;
reg   [31:0] tmp_V_97_reg_1587;
reg   [31:0] tmp_V_98_reg_1592;
reg   [31:0] tmp_V_99_reg_1597;
reg   [31:0] tmp_V_100_reg_1602;
reg   [31:0] tmp_V_101_reg_1607;
reg   [31:0] tmp_V_102_reg_1612;
reg   [31:0] tmp_V_103_reg_1617;
reg   [31:0] tmp_V_104_reg_1622;
reg   [31:0] tmp_V_105_reg_1627;
reg   [31:0] tmp_V_106_reg_1632;
reg   [31:0] tmp_V_107_reg_1637;
reg   [31:0] tmp_V_108_reg_1642;
reg   [25:0] tmp_84_i_reg_1647;
reg   [25:0] tmp_86_i_reg_1652;
reg   [25:0] tmp_88_i_reg_1657;
reg   [25:0] tmp_90_i_reg_1662;
reg   [25:0] tmp_92_i_reg_1667;
reg   [25:0] tmp_98_i_reg_1672;
reg   [25:0] tmp_100_i_reg_1677;
reg   [25:0] tmp_102_i_reg_1682;
reg   [25:0] tmp_104_i_reg_1687;
reg   [25:0] tmp_106_i_reg_1692;
reg   [25:0] tmp_108_i_reg_1697;
reg   [25:0] tmp_110_i_reg_1702;
reg   [25:0] tmp_112_i_reg_1707;
wire   [31:0] p_3_5_i_fu_1222_p2;
reg   [31:0] p_3_5_i_reg_1712;
wire   [31:0] p_3_6_i_fu_1228_p2;
reg   [31:0] p_3_6_i_reg_1717;
wire   [31:0] p_3_14_i_fu_1234_p2;
reg   [31:0] p_3_14_i_reg_1722;
wire   [31:0] var_0_V_fu_1285_p2;
reg   [31:0] var_0_V_reg_1727;
reg    ap_enable_reg_pp0_iter3;
wire   [31:0] var_1_V_fu_1297_p2;
reg   [31:0] var_1_V_reg_1733;
wire   [31:0] var_2_V_fu_1309_p2;
reg   [31:0] var_2_V_reg_1739;
wire   [31:0] var_3_V_fu_1321_p2;
reg   [31:0] var_3_V_reg_1745;
wire   [31:0] var_4_V_fu_1333_p2;
reg   [31:0] var_4_V_reg_1751;
wire   [31:0] var_5_V_fu_1339_p2;
reg   [31:0] var_5_V_reg_1757;
wire   [31:0] var_6_V_fu_1344_p2;
reg   [31:0] var_6_V_reg_1762;
wire   [31:0] var_7_V_fu_1355_p2;
reg   [31:0] var_7_V_reg_1767;
wire   [31:0] var_8_V_fu_1367_p2;
reg   [31:0] var_8_V_reg_1773;
wire   [31:0] var_9_V_fu_1379_p2;
reg   [31:0] var_9_V_reg_1779;
wire   [31:0] var_10_V_fu_1391_p2;
reg   [31:0] var_10_V_reg_1785;
wire   [31:0] var_11_V_fu_1403_p2;
reg   [31:0] var_11_V_reg_1791;
wire   [31:0] var_12_V_fu_1415_p2;
reg   [31:0] var_12_V_reg_1797;
wire   [31:0] var_13_V_fu_1427_p2;
reg   [31:0] var_13_V_reg_1803;
wire   [31:0] var_14_V_fu_1439_p2;
reg   [31:0] var_14_V_reg_1809;
wire   [31:0] var_15_V_fu_1445_p2;
reg   [31:0] var_15_V_reg_1815;
wire   [31:0] tmp27_fu_1456_p2;
reg   [31:0] tmp27_reg_1820;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_condition_pp0_exit_iter3_state5;
reg   [31:0] ap_phi_mux_var_V_0_1_i_phi_fu_493_p4;
reg   [31:0] ap_phi_mux_var_V_1_1_i_phi_fu_504_p4;
reg   [31:0] ap_phi_mux_var_V_2_1_i_phi_fu_515_p4;
reg   [31:0] ap_phi_mux_var_V_3_1_i_phi_fu_526_p4;
reg   [31:0] ap_phi_mux_var_V_4_1_i_phi_fu_537_p4;
reg   [31:0] ap_phi_mux_var_V_5_1_i_phi_fu_548_p4;
reg   [31:0] ap_phi_mux_var_V_6_1_i_phi_fu_559_p4;
reg   [31:0] ap_phi_mux_var_V_7_1_i_phi_fu_570_p4;
reg   [31:0] ap_phi_mux_var_V_8_1_i_phi_fu_581_p4;
reg   [31:0] ap_phi_mux_var_V_9_1_i_phi_fu_592_p4;
reg   [31:0] ap_phi_mux_var_V_10_1_i_phi_fu_603_p4;
reg   [31:0] ap_phi_mux_var_V_11_1_i_phi_fu_614_p4;
reg   [31:0] ap_phi_mux_var_V_12_1_i_phi_fu_625_p4;
reg   [31:0] ap_phi_mux_var_V_13_1_i_phi_fu_636_p4;
reg   [31:0] ap_phi_mux_var_V_14_1_i_phi_fu_647_p4;
reg   [31:0] ap_phi_mux_var_V_15_1_i_phi_fu_658_p4;
reg   [31:0] ap_phi_mux_p_0111_4_i_phi_fu_885_p4;
reg   [31:0] ap_phi_mux_p_0111_1_i_phi_fu_669_p4;
reg   [31:0] ap_phi_mux_var_V_0_2_i_phi_fu_681_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_var_V_0_2_i_reg_677;
reg   [31:0] ap_phi_reg_pp0_iter1_var_V_0_2_i_reg_677;
reg   [31:0] ap_phi_reg_pp0_iter2_var_V_0_2_i_reg_677;
reg   [31:0] ap_phi_reg_pp0_iter3_var_V_0_2_i_reg_677;
reg   [31:0] ap_phi_mux_var_V_1_2_i_phi_fu_693_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_var_V_1_2_i_reg_689;
reg   [31:0] ap_phi_reg_pp0_iter1_var_V_1_2_i_reg_689;
reg   [31:0] ap_phi_reg_pp0_iter2_var_V_1_2_i_reg_689;
reg   [31:0] ap_phi_reg_pp0_iter3_var_V_1_2_i_reg_689;
reg   [31:0] ap_phi_mux_var_V_2_2_i_phi_fu_705_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_var_V_2_2_i_reg_701;
reg   [31:0] ap_phi_reg_pp0_iter1_var_V_2_2_i_reg_701;
reg   [31:0] ap_phi_reg_pp0_iter2_var_V_2_2_i_reg_701;
reg   [31:0] ap_phi_reg_pp0_iter3_var_V_2_2_i_reg_701;
reg   [31:0] ap_phi_mux_var_V_3_2_i_phi_fu_717_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_var_V_3_2_i_reg_713;
reg   [31:0] ap_phi_reg_pp0_iter1_var_V_3_2_i_reg_713;
reg   [31:0] ap_phi_reg_pp0_iter2_var_V_3_2_i_reg_713;
reg   [31:0] ap_phi_reg_pp0_iter3_var_V_3_2_i_reg_713;
reg   [31:0] ap_phi_mux_var_V_4_2_i_phi_fu_729_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_var_V_4_2_i_reg_725;
reg   [31:0] ap_phi_reg_pp0_iter1_var_V_4_2_i_reg_725;
reg   [31:0] ap_phi_reg_pp0_iter2_var_V_4_2_i_reg_725;
reg   [31:0] ap_phi_reg_pp0_iter3_var_V_4_2_i_reg_725;
reg   [31:0] ap_phi_mux_var_V_5_2_i_phi_fu_741_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_var_V_5_2_i_reg_737;
reg   [31:0] ap_phi_reg_pp0_iter1_var_V_5_2_i_reg_737;
reg   [31:0] ap_phi_reg_pp0_iter2_var_V_5_2_i_reg_737;
reg   [31:0] ap_phi_reg_pp0_iter3_var_V_5_2_i_reg_737;
reg   [31:0] ap_phi_mux_var_V_6_2_i_phi_fu_753_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_var_V_6_2_i_reg_749;
reg   [31:0] ap_phi_reg_pp0_iter1_var_V_6_2_i_reg_749;
reg   [31:0] ap_phi_reg_pp0_iter2_var_V_6_2_i_reg_749;
reg   [31:0] ap_phi_reg_pp0_iter3_var_V_6_2_i_reg_749;
reg   [31:0] ap_phi_mux_var_V_7_2_i_phi_fu_765_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_var_V_7_2_i_reg_761;
reg   [31:0] ap_phi_reg_pp0_iter1_var_V_7_2_i_reg_761;
reg   [31:0] ap_phi_reg_pp0_iter2_var_V_7_2_i_reg_761;
reg   [31:0] ap_phi_reg_pp0_iter3_var_V_7_2_i_reg_761;
reg   [31:0] ap_phi_mux_var_V_8_2_i_phi_fu_777_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_var_V_8_2_i_reg_773;
reg   [31:0] ap_phi_reg_pp0_iter1_var_V_8_2_i_reg_773;
reg   [31:0] ap_phi_reg_pp0_iter2_var_V_8_2_i_reg_773;
reg   [31:0] ap_phi_reg_pp0_iter3_var_V_8_2_i_reg_773;
reg   [31:0] ap_phi_mux_var_V_9_2_i_phi_fu_789_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_var_V_9_2_i_reg_785;
reg   [31:0] ap_phi_reg_pp0_iter1_var_V_9_2_i_reg_785;
reg   [31:0] ap_phi_reg_pp0_iter2_var_V_9_2_i_reg_785;
reg   [31:0] ap_phi_reg_pp0_iter3_var_V_9_2_i_reg_785;
reg   [31:0] ap_phi_mux_var_V_10_2_i_phi_fu_801_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_var_V_10_2_i_reg_797;
reg   [31:0] ap_phi_reg_pp0_iter1_var_V_10_2_i_reg_797;
reg   [31:0] ap_phi_reg_pp0_iter2_var_V_10_2_i_reg_797;
reg   [31:0] ap_phi_reg_pp0_iter3_var_V_10_2_i_reg_797;
reg   [31:0] ap_phi_mux_var_V_11_2_i_phi_fu_813_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_var_V_11_2_i_reg_809;
reg   [31:0] ap_phi_reg_pp0_iter1_var_V_11_2_i_reg_809;
reg   [31:0] ap_phi_reg_pp0_iter2_var_V_11_2_i_reg_809;
reg   [31:0] ap_phi_reg_pp0_iter3_var_V_11_2_i_reg_809;
reg   [31:0] ap_phi_mux_var_V_12_2_i_phi_fu_825_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_var_V_12_2_i_reg_821;
reg   [31:0] ap_phi_reg_pp0_iter1_var_V_12_2_i_reg_821;
reg   [31:0] ap_phi_reg_pp0_iter2_var_V_12_2_i_reg_821;
reg   [31:0] ap_phi_reg_pp0_iter3_var_V_12_2_i_reg_821;
reg   [31:0] ap_phi_mux_var_V_13_2_i_phi_fu_837_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_var_V_13_2_i_reg_833;
reg   [31:0] ap_phi_reg_pp0_iter1_var_V_13_2_i_reg_833;
reg   [31:0] ap_phi_reg_pp0_iter2_var_V_13_2_i_reg_833;
reg   [31:0] ap_phi_reg_pp0_iter3_var_V_13_2_i_reg_833;
reg   [31:0] ap_phi_mux_var_V_14_2_i_phi_fu_849_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_var_V_14_2_i_reg_845;
reg   [31:0] ap_phi_reg_pp0_iter1_var_V_14_2_i_reg_845;
reg   [31:0] ap_phi_reg_pp0_iter2_var_V_14_2_i_reg_845;
reg   [31:0] ap_phi_reg_pp0_iter3_var_V_14_2_i_reg_845;
reg   [31:0] ap_phi_mux_var_V_15_2_i_phi_fu_861_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_var_V_15_2_i_reg_857;
reg   [31:0] ap_phi_reg_pp0_iter1_var_V_15_2_i_reg_857;
reg   [31:0] ap_phi_reg_pp0_iter2_var_V_15_2_i_reg_857;
reg   [31:0] ap_phi_reg_pp0_iter3_var_V_15_2_i_reg_857;
wire   [31:0] ap_phi_reg_pp0_iter0_p_0111_2_i_reg_869;
reg   [31:0] ap_phi_reg_pp0_iter1_p_0111_2_i_reg_869;
reg   [31:0] ap_phi_reg_pp0_iter2_p_0111_2_i_reg_869;
reg   [31:0] ap_phi_reg_pp0_iter3_p_0111_2_i_reg_869;
reg   [31:0] ap_phi_reg_pp0_iter4_p_0111_2_i_reg_869;
wire   [31:0] tmp_V_109_fu_1526_p2;
wire   [31:0] ap_phi_reg_pp0_iter4_p_0111_4_i_reg_881;
reg    ap_block_pp0_stage0_01001;
reg   [31:0] tmp_V_fu_340;
wire   [35:0] tmp_fu_901_p3;
wire   [37:0] p_shl_fu_893_p3;
wire   [37:0] p_shl2_fu_909_p1;
wire   [0:0] tmp_i3_fu_930_p2;
wire   [5:0] l_i_mid2_fu_936_p3;
wire   [31:0] read_V_i_fu_970_p2;
wire   [31:0] read_V_1_i_fu_985_p2;
wire   [31:0] read_V_2_i_fu_1000_p2;
wire   [31:0] read_V_3_i_fu_1015_p2;
wire   [31:0] read_V_4_i_fu_1030_p2;
wire   [31:0] read_V_5_i_fu_1045_p2;
wire   [25:0] tmp_94_i_fu_1050_p4;
wire   [31:0] read_V_6_i_fu_1064_p2;
wire   [25:0] tmp_96_i_fu_1069_p4;
wire   [31:0] read_V_7_i_fu_1083_p2;
wire   [31:0] read_V_8_i_fu_1098_p2;
wire   [31:0] read_V_9_i_fu_1113_p2;
wire   [31:0] read_V_i_34_fu_1128_p2;
wire   [31:0] read_V_10_i_fu_1143_p2;
wire   [31:0] read_V_11_i_fu_1158_p2;
wire   [31:0] read_V_12_i_fu_1173_p2;
wire   [31:0] read_V_13_i_fu_1188_p2;
wire   [31:0] read_V_14_i_fu_1203_p2;
wire   [25:0] tmp_114_i_fu_1208_p4;
wire  signed [25:0] p_3_5_i_fu_1222_p0;
wire  signed [31:0] y_5_V_fu_1060_p1;
wire  signed [25:0] p_3_5_i_fu_1222_p1;
wire  signed [25:0] p_3_6_i_fu_1228_p0;
wire  signed [31:0] y_6_V_fu_1079_p1;
wire  signed [25:0] p_3_6_i_fu_1228_p1;
wire  signed [25:0] p_3_14_i_fu_1234_p0;
wire  signed [31:0] r_V_i_fu_1218_p1;
wire  signed [25:0] p_3_14_i_fu_1234_p1;
wire  signed [25:0] p_3_i_fu_1279_p0;
wire  signed [31:0] y_0_V_fu_1240_p1;
wire  signed [25:0] p_3_i_fu_1279_p1;
wire   [31:0] p_3_i_fu_1279_p2;
wire  signed [25:0] p_3_1_i_fu_1291_p0;
wire  signed [31:0] y_1_V_fu_1243_p1;
wire  signed [25:0] p_3_1_i_fu_1291_p1;
wire   [31:0] p_3_1_i_fu_1291_p2;
wire  signed [25:0] p_3_2_i_fu_1303_p0;
wire  signed [31:0] y_2_V_fu_1246_p1;
wire  signed [25:0] p_3_2_i_fu_1303_p1;
wire   [31:0] p_3_2_i_fu_1303_p2;
wire  signed [25:0] p_3_3_i_fu_1315_p0;
wire  signed [31:0] y_3_V_fu_1249_p1;
wire  signed [25:0] p_3_3_i_fu_1315_p1;
wire   [31:0] p_3_3_i_fu_1315_p2;
wire  signed [25:0] p_3_4_i_fu_1327_p0;
wire  signed [31:0] y_4_V_fu_1252_p1;
wire  signed [25:0] p_3_4_i_fu_1327_p1;
wire   [31:0] p_3_4_i_fu_1327_p2;
wire  signed [25:0] p_3_7_i_fu_1349_p0;
wire  signed [31:0] y_7_V_fu_1255_p1;
wire  signed [25:0] p_3_7_i_fu_1349_p1;
wire   [31:0] p_3_7_i_fu_1349_p2;
wire  signed [25:0] p_3_8_i_fu_1361_p0;
wire  signed [31:0] y_8_V_fu_1258_p1;
wire  signed [25:0] p_3_8_i_fu_1361_p1;
wire   [31:0] p_3_8_i_fu_1361_p2;
wire  signed [25:0] p_3_9_i_fu_1373_p0;
wire  signed [31:0] y_9_V_fu_1261_p1;
wire  signed [25:0] p_3_9_i_fu_1373_p1;
wire   [31:0] p_3_9_i_fu_1373_p2;
wire  signed [25:0] p_3_i_35_fu_1385_p0;
wire  signed [31:0] y_10_V_fu_1264_p1;
wire  signed [25:0] p_3_i_35_fu_1385_p1;
wire   [31:0] p_3_i_35_fu_1385_p2;
wire  signed [25:0] p_3_10_i_fu_1397_p0;
wire  signed [31:0] y_11_V_fu_1267_p1;
wire  signed [25:0] p_3_10_i_fu_1397_p1;
wire   [31:0] p_3_10_i_fu_1397_p2;
wire  signed [25:0] p_3_11_i_fu_1409_p0;
wire  signed [31:0] y_12_V_fu_1270_p1;
wire  signed [25:0] p_3_11_i_fu_1409_p1;
wire   [31:0] p_3_11_i_fu_1409_p2;
wire  signed [25:0] p_3_12_i_fu_1421_p0;
wire  signed [31:0] y_13_V_fu_1273_p1;
wire  signed [25:0] p_3_12_i_fu_1421_p1;
wire   [31:0] p_3_12_i_fu_1421_p2;
wire  signed [25:0] p_3_13_i_fu_1433_p0;
wire  signed [31:0] y_14_V_fu_1276_p1;
wire  signed [25:0] p_3_13_i_fu_1433_p1;
wire   [31:0] p_3_13_i_fu_1433_p2;
wire   [31:0] tmp28_fu_1450_p2;
wire   [31:0] tmp17_fu_1466_p2;
wire   [31:0] tmp16_fu_1462_p2;
wire   [31:0] tmp20_fu_1480_p2;
wire   [31:0] tmp19_fu_1476_p2;
wire   [31:0] tmp18_fu_1484_p2;
wire   [31:0] tmp15_fu_1470_p2;
wire   [31:0] tmp24_fu_1501_p2;
wire   [31:0] tmp23_fu_1496_p2;
wire   [31:0] tmp26_fu_1511_p2;
wire   [31:0] tmp25_fu_1515_p2;
wire   [31:0] tmp22_fu_1505_p2;
wire   [31:0] tmp21_fu_1520_p2;
wire   [31:0] tmp14_fu_1490_p2;
wire    ap_CS_fsm_state7;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_480;
reg    ap_condition_502;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_fu_919_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (n_pipe2_V_V_full_n == 1'b0) | (n_pipe1_V_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter3_state5)) | (~((real_start == 1'b0) | (n_pipe2_V_V_full_n == 1'b0) | (n_pipe1_V_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter3_state5))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter2;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if ((~((real_start == 1'b0) | (n_pipe2_V_V_full_n == 1'b0) | (n_pipe1_V_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_502)) begin
        if (((tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_p_0111_2_i_reg_869 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_p_0111_2_i_reg_869 <= ap_phi_reg_pp0_iter1_p_0111_2_i_reg_869;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_502)) begin
        if (((tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_var_V_0_2_i_reg_677 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_var_V_0_2_i_reg_677 <= ap_phi_reg_pp0_iter1_var_V_0_2_i_reg_677;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_502)) begin
        if (((tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_var_V_10_2_i_reg_797 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_var_V_10_2_i_reg_797 <= ap_phi_reg_pp0_iter1_var_V_10_2_i_reg_797;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_502)) begin
        if (((tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_var_V_11_2_i_reg_809 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_var_V_11_2_i_reg_809 <= ap_phi_reg_pp0_iter1_var_V_11_2_i_reg_809;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_502)) begin
        if (((tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_var_V_12_2_i_reg_821 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_var_V_12_2_i_reg_821 <= ap_phi_reg_pp0_iter1_var_V_12_2_i_reg_821;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_502)) begin
        if (((tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_var_V_13_2_i_reg_833 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_var_V_13_2_i_reg_833 <= ap_phi_reg_pp0_iter1_var_V_13_2_i_reg_833;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_502)) begin
        if (((tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_var_V_14_2_i_reg_845 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_var_V_14_2_i_reg_845 <= ap_phi_reg_pp0_iter1_var_V_14_2_i_reg_845;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_502)) begin
        if (((tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_var_V_15_2_i_reg_857 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_var_V_15_2_i_reg_857 <= ap_phi_reg_pp0_iter1_var_V_15_2_i_reg_857;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_502)) begin
        if (((tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_var_V_1_2_i_reg_689 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_var_V_1_2_i_reg_689 <= ap_phi_reg_pp0_iter1_var_V_1_2_i_reg_689;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_502)) begin
        if (((tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_var_V_2_2_i_reg_701 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_var_V_2_2_i_reg_701 <= ap_phi_reg_pp0_iter1_var_V_2_2_i_reg_701;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_502)) begin
        if (((tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_var_V_3_2_i_reg_713 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_var_V_3_2_i_reg_713 <= ap_phi_reg_pp0_iter1_var_V_3_2_i_reg_713;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_502)) begin
        if (((tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_var_V_4_2_i_reg_725 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_var_V_4_2_i_reg_725 <= ap_phi_reg_pp0_iter1_var_V_4_2_i_reg_725;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_502)) begin
        if (((tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_var_V_5_2_i_reg_737 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_var_V_5_2_i_reg_737 <= ap_phi_reg_pp0_iter1_var_V_5_2_i_reg_737;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_502)) begin
        if (((tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_var_V_6_2_i_reg_749 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_var_V_6_2_i_reg_749 <= ap_phi_reg_pp0_iter1_var_V_6_2_i_reg_749;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_502)) begin
        if (((tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_var_V_7_2_i_reg_761 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_var_V_7_2_i_reg_761 <= ap_phi_reg_pp0_iter1_var_V_7_2_i_reg_761;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_502)) begin
        if (((tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_var_V_8_2_i_reg_773 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_var_V_8_2_i_reg_773 <= ap_phi_reg_pp0_iter1_var_V_8_2_i_reg_773;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_502)) begin
        if (((tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_var_V_9_2_i_reg_785 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_var_V_9_2_i_reg_785 <= ap_phi_reg_pp0_iter1_var_V_9_2_i_reg_785;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((tmp_18_i_reg_1554_pp0_iter2_reg == 1'd0) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_p_0111_2_i_reg_869 <= ap_phi_mux_p_0111_1_i_phi_fu_669_p4;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_p_0111_2_i_reg_869 <= ap_phi_reg_pp0_iter3_p_0111_2_i_reg_869;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_fu_919_p2 == 1'd0))) begin
        indvar_flatten_reg_467 <= indvar_flatten_next_fu_924_p2;
    end else if ((~((real_start == 1'b0) | (n_pipe2_V_V_full_n == 1'b0) | (n_pipe1_V_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_467 <= 38'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_fu_919_p2 == 1'd0))) begin
        l_i_reg_478 <= l_fu_956_p2;
    end else if ((~((real_start == 1'b0) | (n_pipe2_V_V_full_n == 1'b0) | (n_pipe1_V_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        l_i_reg_478 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_p_0111_2_i_reg_869 <= ap_phi_reg_pp0_iter0_p_0111_2_i_reg_869;
        ap_phi_reg_pp0_iter1_var_V_0_2_i_reg_677 <= ap_phi_reg_pp0_iter0_var_V_0_2_i_reg_677;
        ap_phi_reg_pp0_iter1_var_V_10_2_i_reg_797 <= ap_phi_reg_pp0_iter0_var_V_10_2_i_reg_797;
        ap_phi_reg_pp0_iter1_var_V_11_2_i_reg_809 <= ap_phi_reg_pp0_iter0_var_V_11_2_i_reg_809;
        ap_phi_reg_pp0_iter1_var_V_12_2_i_reg_821 <= ap_phi_reg_pp0_iter0_var_V_12_2_i_reg_821;
        ap_phi_reg_pp0_iter1_var_V_13_2_i_reg_833 <= ap_phi_reg_pp0_iter0_var_V_13_2_i_reg_833;
        ap_phi_reg_pp0_iter1_var_V_14_2_i_reg_845 <= ap_phi_reg_pp0_iter0_var_V_14_2_i_reg_845;
        ap_phi_reg_pp0_iter1_var_V_15_2_i_reg_857 <= ap_phi_reg_pp0_iter0_var_V_15_2_i_reg_857;
        ap_phi_reg_pp0_iter1_var_V_1_2_i_reg_689 <= ap_phi_reg_pp0_iter0_var_V_1_2_i_reg_689;
        ap_phi_reg_pp0_iter1_var_V_2_2_i_reg_701 <= ap_phi_reg_pp0_iter0_var_V_2_2_i_reg_701;
        ap_phi_reg_pp0_iter1_var_V_3_2_i_reg_713 <= ap_phi_reg_pp0_iter0_var_V_3_2_i_reg_713;
        ap_phi_reg_pp0_iter1_var_V_4_2_i_reg_725 <= ap_phi_reg_pp0_iter0_var_V_4_2_i_reg_725;
        ap_phi_reg_pp0_iter1_var_V_5_2_i_reg_737 <= ap_phi_reg_pp0_iter0_var_V_5_2_i_reg_737;
        ap_phi_reg_pp0_iter1_var_V_6_2_i_reg_749 <= ap_phi_reg_pp0_iter0_var_V_6_2_i_reg_749;
        ap_phi_reg_pp0_iter1_var_V_7_2_i_reg_761 <= ap_phi_reg_pp0_iter0_var_V_7_2_i_reg_761;
        ap_phi_reg_pp0_iter1_var_V_8_2_i_reg_773 <= ap_phi_reg_pp0_iter0_var_V_8_2_i_reg_773;
        ap_phi_reg_pp0_iter1_var_V_9_2_i_reg_785 <= ap_phi_reg_pp0_iter0_var_V_9_2_i_reg_785;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_p_0111_2_i_reg_869 <= ap_phi_reg_pp0_iter2_p_0111_2_i_reg_869;
        ap_phi_reg_pp0_iter3_var_V_0_2_i_reg_677 <= ap_phi_reg_pp0_iter2_var_V_0_2_i_reg_677;
        ap_phi_reg_pp0_iter3_var_V_10_2_i_reg_797 <= ap_phi_reg_pp0_iter2_var_V_10_2_i_reg_797;
        ap_phi_reg_pp0_iter3_var_V_11_2_i_reg_809 <= ap_phi_reg_pp0_iter2_var_V_11_2_i_reg_809;
        ap_phi_reg_pp0_iter3_var_V_12_2_i_reg_821 <= ap_phi_reg_pp0_iter2_var_V_12_2_i_reg_821;
        ap_phi_reg_pp0_iter3_var_V_13_2_i_reg_833 <= ap_phi_reg_pp0_iter2_var_V_13_2_i_reg_833;
        ap_phi_reg_pp0_iter3_var_V_14_2_i_reg_845 <= ap_phi_reg_pp0_iter2_var_V_14_2_i_reg_845;
        ap_phi_reg_pp0_iter3_var_V_15_2_i_reg_857 <= ap_phi_reg_pp0_iter2_var_V_15_2_i_reg_857;
        ap_phi_reg_pp0_iter3_var_V_1_2_i_reg_689 <= ap_phi_reg_pp0_iter2_var_V_1_2_i_reg_689;
        ap_phi_reg_pp0_iter3_var_V_2_2_i_reg_701 <= ap_phi_reg_pp0_iter2_var_V_2_2_i_reg_701;
        ap_phi_reg_pp0_iter3_var_V_3_2_i_reg_713 <= ap_phi_reg_pp0_iter2_var_V_3_2_i_reg_713;
        ap_phi_reg_pp0_iter3_var_V_4_2_i_reg_725 <= ap_phi_reg_pp0_iter2_var_V_4_2_i_reg_725;
        ap_phi_reg_pp0_iter3_var_V_5_2_i_reg_737 <= ap_phi_reg_pp0_iter2_var_V_5_2_i_reg_737;
        ap_phi_reg_pp0_iter3_var_V_6_2_i_reg_749 <= ap_phi_reg_pp0_iter2_var_V_6_2_i_reg_749;
        ap_phi_reg_pp0_iter3_var_V_7_2_i_reg_761 <= ap_phi_reg_pp0_iter2_var_V_7_2_i_reg_761;
        ap_phi_reg_pp0_iter3_var_V_8_2_i_reg_773 <= ap_phi_reg_pp0_iter2_var_V_8_2_i_reg_773;
        ap_phi_reg_pp0_iter3_var_V_9_2_i_reg_785 <= ap_phi_reg_pp0_iter2_var_V_9_2_i_reg_785;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (n_pipe2_V_V_full_n == 1'b0) | (n_pipe1_V_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bound_reg_1540[37 : 4] <= bound_fu_913_p2[37 : 4];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond_flatten_reg_1545 <= exitcond_flatten_fu_919_p2;
        exitcond_flatten_reg_1545_pp0_iter1_reg <= exitcond_flatten_reg_1545;
        tmp_18_i_reg_1554_pp0_iter1_reg <= tmp_18_i_reg_1554;
        tmp_19_i_reg_1558_pp0_iter1_reg <= tmp_19_i_reg_1558;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exitcond_flatten_reg_1545_pp0_iter2_reg <= exitcond_flatten_reg_1545_pp0_iter1_reg;
        exitcond_flatten_reg_1545_pp0_iter3_reg <= exitcond_flatten_reg_1545_pp0_iter2_reg;
        tmp_18_i_reg_1554_pp0_iter2_reg <= tmp_18_i_reg_1554_pp0_iter1_reg;
        tmp_19_i_reg_1558_pp0_iter2_reg <= tmp_19_i_reg_1558_pp0_iter1_reg;
        tmp_19_i_reg_1558_pp0_iter3_reg <= tmp_19_i_reg_1558_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0))) begin
        p_0111_1_i_reg_665 <= ap_phi_mux_p_0111_4_i_phi_fu_885_p4;
        var_V_0_1_i_reg_489 <= var_0_V_reg_1727;
        var_V_10_1_i_reg_599 <= var_10_V_reg_1785;
        var_V_11_1_i_reg_610 <= var_11_V_reg_1791;
        var_V_12_1_i_reg_621 <= var_12_V_reg_1797;
        var_V_13_1_i_reg_632 <= var_13_V_reg_1803;
        var_V_14_1_i_reg_643 <= var_14_V_reg_1809;
        var_V_15_1_i_reg_654 <= var_15_V_reg_1815;
        var_V_1_1_i_reg_500 <= var_1_V_reg_1733;
        var_V_2_1_i_reg_511 <= var_2_V_reg_1739;
        var_V_3_1_i_reg_522 <= var_3_V_reg_1745;
        var_V_4_1_i_reg_533 <= var_4_V_reg_1751;
        var_V_5_1_i_reg_544 <= var_5_V_reg_1757;
        var_V_6_1_i_reg_555 <= var_6_V_reg_1762;
        var_V_7_1_i_reg_566 <= var_7_V_reg_1767;
        var_V_8_1_i_reg_577 <= var_8_V_reg_1773;
        var_V_9_1_i_reg_588 <= var_9_V_reg_1779;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten_reg_1545_pp0_iter1_reg == 1'd0))) begin
        p_3_14_i_reg_1722 <= p_3_14_i_fu_1234_p2;
        p_3_5_i_reg_1712 <= p_3_5_i_fu_1222_p2;
        p_3_6_i_reg_1717 <= p_3_6_i_fu_1228_p2;
        tmp_100_i_reg_1677 <= {{read_V_8_i_fu_1098_p2[31:6]}};
        tmp_102_i_reg_1682 <= {{read_V_9_i_fu_1113_p2[31:6]}};
        tmp_104_i_reg_1687 <= {{read_V_i_34_fu_1128_p2[31:6]}};
        tmp_106_i_reg_1692 <= {{read_V_10_i_fu_1143_p2[31:6]}};
        tmp_108_i_reg_1697 <= {{read_V_11_i_fu_1158_p2[31:6]}};
        tmp_110_i_reg_1702 <= {{read_V_12_i_fu_1173_p2[31:6]}};
        tmp_112_i_reg_1707 <= {{read_V_13_i_fu_1188_p2[31:6]}};
        tmp_84_i_reg_1647 <= {{read_V_i_fu_970_p2[31:6]}};
        tmp_86_i_reg_1652 <= {{read_V_1_i_fu_985_p2[31:6]}};
        tmp_88_i_reg_1657 <= {{read_V_2_i_fu_1000_p2[31:6]}};
        tmp_90_i_reg_1662 <= {{read_V_3_i_fu_1015_p2[31:6]}};
        tmp_92_i_reg_1667 <= {{read_V_4_i_fu_1030_p2[31:6]}};
        tmp_98_i_reg_1672 <= {{read_V_7_i_fu_1083_p2[31:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_19_i_reg_1558_pp0_iter2_reg == 1'd1) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0))) begin
        tmp27_reg_1820 <= tmp27_fu_1456_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_fu_919_p2 == 1'd0))) begin
        tmp_18_i_reg_1554 <= tmp_18_i_fu_944_p2;
        tmp_19_i_reg_1558 <= tmp_19_i_fu_950_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0))) begin
        tmp_V_100_reg_1602 <= in_compute_V_V_7_dout;
        tmp_V_101_reg_1607 <= in_compute_V_V_8_dout;
        tmp_V_102_reg_1612 <= in_compute_V_V_9_dout;
        tmp_V_103_reg_1617 <= in_compute_V_V_10_dout;
        tmp_V_104_reg_1622 <= in_compute_V_V_11_dout;
        tmp_V_105_reg_1627 <= in_compute_V_V_12_dout;
        tmp_V_106_reg_1632 <= in_compute_V_V_13_dout;
        tmp_V_107_reg_1637 <= in_compute_V_V_14_dout;
        tmp_V_108_reg_1642 <= in_compute_V_V_15_dout;
        tmp_V_93_reg_1567 <= in_compute_V_V_0_dout;
        tmp_V_94_reg_1572 <= in_compute_V_V_1_dout;
        tmp_V_95_reg_1577 <= in_compute_V_V_2_dout;
        tmp_V_96_reg_1582 <= in_compute_V_V_3_dout;
        tmp_V_97_reg_1587 <= in_compute_V_V_4_dout;
        tmp_V_98_reg_1592 <= in_compute_V_V_5_dout;
        tmp_V_99_reg_1597 <= in_compute_V_V_6_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0))) begin
        tmp_V_fu_340 <= mean_pipe1_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0))) begin
        var_0_V_reg_1727 <= var_0_V_fu_1285_p2;
        var_10_V_reg_1785 <= var_10_V_fu_1391_p2;
        var_11_V_reg_1791 <= var_11_V_fu_1403_p2;
        var_12_V_reg_1797 <= var_12_V_fu_1415_p2;
        var_13_V_reg_1803 <= var_13_V_fu_1427_p2;
        var_14_V_reg_1809 <= var_14_V_fu_1439_p2;
        var_15_V_reg_1815 <= var_15_V_fu_1445_p2;
        var_1_V_reg_1733 <= var_1_V_fu_1297_p2;
        var_2_V_reg_1739 <= var_2_V_fu_1309_p2;
        var_3_V_reg_1745 <= var_3_V_fu_1321_p2;
        var_4_V_reg_1751 <= var_4_V_fu_1333_p2;
        var_5_V_reg_1757 <= var_5_V_fu_1339_p2;
        var_6_V_reg_1762 <= var_6_V_fu_1344_p2;
        var_7_V_reg_1767 <= var_7_V_fu_1355_p2;
        var_8_V_reg_1773 <= var_8_V_fu_1367_p2;
        var_9_V_reg_1779 <= var_9_V_fu_1379_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_condition_pp0_exit_iter3_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter3_state5 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_p_0111_1_i_phi_fu_669_p4 = ap_phi_mux_p_0111_4_i_phi_fu_885_p4;
    end else begin
        ap_phi_mux_p_0111_1_i_phi_fu_669_p4 = p_0111_1_i_reg_665;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_480)) begin
        if ((tmp_19_i_reg_1558_pp0_iter3_reg == 1'd0)) begin
            ap_phi_mux_p_0111_4_i_phi_fu_885_p4 = ap_phi_reg_pp0_iter4_p_0111_2_i_reg_869;
        end else if ((tmp_19_i_reg_1558_pp0_iter3_reg == 1'd1)) begin
            ap_phi_mux_p_0111_4_i_phi_fu_885_p4 = tmp_V_109_fu_1526_p2;
        end else begin
            ap_phi_mux_p_0111_4_i_phi_fu_885_p4 = ap_phi_reg_pp0_iter4_p_0111_4_i_reg_881;
        end
    end else begin
        ap_phi_mux_p_0111_4_i_phi_fu_885_p4 = ap_phi_reg_pp0_iter4_p_0111_4_i_reg_881;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_0_1_i_phi_fu_493_p4 = var_0_V_reg_1727;
    end else begin
        ap_phi_mux_var_V_0_1_i_phi_fu_493_p4 = var_V_0_1_i_reg_489;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_18_i_reg_1554_pp0_iter2_reg == 1'd0) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_0_2_i_phi_fu_681_p4 = ap_phi_mux_var_V_0_1_i_phi_fu_493_p4;
    end else begin
        ap_phi_mux_var_V_0_2_i_phi_fu_681_p4 = ap_phi_reg_pp0_iter3_var_V_0_2_i_reg_677;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_10_1_i_phi_fu_603_p4 = var_10_V_reg_1785;
    end else begin
        ap_phi_mux_var_V_10_1_i_phi_fu_603_p4 = var_V_10_1_i_reg_599;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_18_i_reg_1554_pp0_iter2_reg == 1'd0) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_10_2_i_phi_fu_801_p4 = ap_phi_mux_var_V_10_1_i_phi_fu_603_p4;
    end else begin
        ap_phi_mux_var_V_10_2_i_phi_fu_801_p4 = ap_phi_reg_pp0_iter3_var_V_10_2_i_reg_797;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_11_1_i_phi_fu_614_p4 = var_11_V_reg_1791;
    end else begin
        ap_phi_mux_var_V_11_1_i_phi_fu_614_p4 = var_V_11_1_i_reg_610;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_18_i_reg_1554_pp0_iter2_reg == 1'd0) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_11_2_i_phi_fu_813_p4 = ap_phi_mux_var_V_11_1_i_phi_fu_614_p4;
    end else begin
        ap_phi_mux_var_V_11_2_i_phi_fu_813_p4 = ap_phi_reg_pp0_iter3_var_V_11_2_i_reg_809;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_12_1_i_phi_fu_625_p4 = var_12_V_reg_1797;
    end else begin
        ap_phi_mux_var_V_12_1_i_phi_fu_625_p4 = var_V_12_1_i_reg_621;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_18_i_reg_1554_pp0_iter2_reg == 1'd0) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_12_2_i_phi_fu_825_p4 = ap_phi_mux_var_V_12_1_i_phi_fu_625_p4;
    end else begin
        ap_phi_mux_var_V_12_2_i_phi_fu_825_p4 = ap_phi_reg_pp0_iter3_var_V_12_2_i_reg_821;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_13_1_i_phi_fu_636_p4 = var_13_V_reg_1803;
    end else begin
        ap_phi_mux_var_V_13_1_i_phi_fu_636_p4 = var_V_13_1_i_reg_632;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_18_i_reg_1554_pp0_iter2_reg == 1'd0) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_13_2_i_phi_fu_837_p4 = ap_phi_mux_var_V_13_1_i_phi_fu_636_p4;
    end else begin
        ap_phi_mux_var_V_13_2_i_phi_fu_837_p4 = ap_phi_reg_pp0_iter3_var_V_13_2_i_reg_833;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_14_1_i_phi_fu_647_p4 = var_14_V_reg_1809;
    end else begin
        ap_phi_mux_var_V_14_1_i_phi_fu_647_p4 = var_V_14_1_i_reg_643;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_18_i_reg_1554_pp0_iter2_reg == 1'd0) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_14_2_i_phi_fu_849_p4 = ap_phi_mux_var_V_14_1_i_phi_fu_647_p4;
    end else begin
        ap_phi_mux_var_V_14_2_i_phi_fu_849_p4 = ap_phi_reg_pp0_iter3_var_V_14_2_i_reg_845;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_15_1_i_phi_fu_658_p4 = var_15_V_reg_1815;
    end else begin
        ap_phi_mux_var_V_15_1_i_phi_fu_658_p4 = var_V_15_1_i_reg_654;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_18_i_reg_1554_pp0_iter2_reg == 1'd0) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_15_2_i_phi_fu_861_p4 = ap_phi_mux_var_V_15_1_i_phi_fu_658_p4;
    end else begin
        ap_phi_mux_var_V_15_2_i_phi_fu_861_p4 = ap_phi_reg_pp0_iter3_var_V_15_2_i_reg_857;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_1_1_i_phi_fu_504_p4 = var_1_V_reg_1733;
    end else begin
        ap_phi_mux_var_V_1_1_i_phi_fu_504_p4 = var_V_1_1_i_reg_500;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_18_i_reg_1554_pp0_iter2_reg == 1'd0) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_1_2_i_phi_fu_693_p4 = ap_phi_mux_var_V_1_1_i_phi_fu_504_p4;
    end else begin
        ap_phi_mux_var_V_1_2_i_phi_fu_693_p4 = ap_phi_reg_pp0_iter3_var_V_1_2_i_reg_689;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_2_1_i_phi_fu_515_p4 = var_2_V_reg_1739;
    end else begin
        ap_phi_mux_var_V_2_1_i_phi_fu_515_p4 = var_V_2_1_i_reg_511;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_18_i_reg_1554_pp0_iter2_reg == 1'd0) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_2_2_i_phi_fu_705_p4 = ap_phi_mux_var_V_2_1_i_phi_fu_515_p4;
    end else begin
        ap_phi_mux_var_V_2_2_i_phi_fu_705_p4 = ap_phi_reg_pp0_iter3_var_V_2_2_i_reg_701;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_3_1_i_phi_fu_526_p4 = var_3_V_reg_1745;
    end else begin
        ap_phi_mux_var_V_3_1_i_phi_fu_526_p4 = var_V_3_1_i_reg_522;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_18_i_reg_1554_pp0_iter2_reg == 1'd0) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_3_2_i_phi_fu_717_p4 = ap_phi_mux_var_V_3_1_i_phi_fu_526_p4;
    end else begin
        ap_phi_mux_var_V_3_2_i_phi_fu_717_p4 = ap_phi_reg_pp0_iter3_var_V_3_2_i_reg_713;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_4_1_i_phi_fu_537_p4 = var_4_V_reg_1751;
    end else begin
        ap_phi_mux_var_V_4_1_i_phi_fu_537_p4 = var_V_4_1_i_reg_533;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_18_i_reg_1554_pp0_iter2_reg == 1'd0) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_4_2_i_phi_fu_729_p4 = ap_phi_mux_var_V_4_1_i_phi_fu_537_p4;
    end else begin
        ap_phi_mux_var_V_4_2_i_phi_fu_729_p4 = ap_phi_reg_pp0_iter3_var_V_4_2_i_reg_725;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_5_1_i_phi_fu_548_p4 = var_5_V_reg_1757;
    end else begin
        ap_phi_mux_var_V_5_1_i_phi_fu_548_p4 = var_V_5_1_i_reg_544;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_18_i_reg_1554_pp0_iter2_reg == 1'd0) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_5_2_i_phi_fu_741_p4 = ap_phi_mux_var_V_5_1_i_phi_fu_548_p4;
    end else begin
        ap_phi_mux_var_V_5_2_i_phi_fu_741_p4 = ap_phi_reg_pp0_iter3_var_V_5_2_i_reg_737;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_6_1_i_phi_fu_559_p4 = var_6_V_reg_1762;
    end else begin
        ap_phi_mux_var_V_6_1_i_phi_fu_559_p4 = var_V_6_1_i_reg_555;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_18_i_reg_1554_pp0_iter2_reg == 1'd0) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_6_2_i_phi_fu_753_p4 = ap_phi_mux_var_V_6_1_i_phi_fu_559_p4;
    end else begin
        ap_phi_mux_var_V_6_2_i_phi_fu_753_p4 = ap_phi_reg_pp0_iter3_var_V_6_2_i_reg_749;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_7_1_i_phi_fu_570_p4 = var_7_V_reg_1767;
    end else begin
        ap_phi_mux_var_V_7_1_i_phi_fu_570_p4 = var_V_7_1_i_reg_566;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_18_i_reg_1554_pp0_iter2_reg == 1'd0) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_7_2_i_phi_fu_765_p4 = ap_phi_mux_var_V_7_1_i_phi_fu_570_p4;
    end else begin
        ap_phi_mux_var_V_7_2_i_phi_fu_765_p4 = ap_phi_reg_pp0_iter3_var_V_7_2_i_reg_761;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_8_1_i_phi_fu_581_p4 = var_8_V_reg_1773;
    end else begin
        ap_phi_mux_var_V_8_1_i_phi_fu_581_p4 = var_V_8_1_i_reg_577;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_18_i_reg_1554_pp0_iter2_reg == 1'd0) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_8_2_i_phi_fu_777_p4 = ap_phi_mux_var_V_8_1_i_phi_fu_581_p4;
    end else begin
        ap_phi_mux_var_V_8_2_i_phi_fu_777_p4 = ap_phi_reg_pp0_iter3_var_V_8_2_i_reg_773;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_9_1_i_phi_fu_592_p4 = var_9_V_reg_1779;
    end else begin
        ap_phi_mux_var_V_9_1_i_phi_fu_592_p4 = var_V_9_1_i_reg_588;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_18_i_reg_1554_pp0_iter2_reg == 1'd0) & (exitcond_flatten_reg_1545_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_var_V_9_2_i_phi_fu_789_p4 = ap_phi_mux_var_V_9_1_i_phi_fu_592_p4;
    end else begin
        ap_phi_mux_var_V_9_2_i_phi_fu_789_p4 = ap_phi_reg_pp0_iter3_var_V_9_2_i_reg_785;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_compute_V_V_0_blk_n = in_compute_V_V_0_empty_n;
    end else begin
        in_compute_V_V_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0))) begin
        in_compute_V_V_0_read = 1'b1;
    end else begin
        in_compute_V_V_0_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_compute_V_V_10_blk_n = in_compute_V_V_10_empty_n;
    end else begin
        in_compute_V_V_10_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0))) begin
        in_compute_V_V_10_read = 1'b1;
    end else begin
        in_compute_V_V_10_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_compute_V_V_11_blk_n = in_compute_V_V_11_empty_n;
    end else begin
        in_compute_V_V_11_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0))) begin
        in_compute_V_V_11_read = 1'b1;
    end else begin
        in_compute_V_V_11_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_compute_V_V_12_blk_n = in_compute_V_V_12_empty_n;
    end else begin
        in_compute_V_V_12_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0))) begin
        in_compute_V_V_12_read = 1'b1;
    end else begin
        in_compute_V_V_12_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_compute_V_V_13_blk_n = in_compute_V_V_13_empty_n;
    end else begin
        in_compute_V_V_13_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0))) begin
        in_compute_V_V_13_read = 1'b1;
    end else begin
        in_compute_V_V_13_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_compute_V_V_14_blk_n = in_compute_V_V_14_empty_n;
    end else begin
        in_compute_V_V_14_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0))) begin
        in_compute_V_V_14_read = 1'b1;
    end else begin
        in_compute_V_V_14_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_compute_V_V_15_blk_n = in_compute_V_V_15_empty_n;
    end else begin
        in_compute_V_V_15_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0))) begin
        in_compute_V_V_15_read = 1'b1;
    end else begin
        in_compute_V_V_15_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_compute_V_V_1_blk_n = in_compute_V_V_1_empty_n;
    end else begin
        in_compute_V_V_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0))) begin
        in_compute_V_V_1_read = 1'b1;
    end else begin
        in_compute_V_V_1_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_compute_V_V_2_blk_n = in_compute_V_V_2_empty_n;
    end else begin
        in_compute_V_V_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0))) begin
        in_compute_V_V_2_read = 1'b1;
    end else begin
        in_compute_V_V_2_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_compute_V_V_3_blk_n = in_compute_V_V_3_empty_n;
    end else begin
        in_compute_V_V_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0))) begin
        in_compute_V_V_3_read = 1'b1;
    end else begin
        in_compute_V_V_3_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_compute_V_V_4_blk_n = in_compute_V_V_4_empty_n;
    end else begin
        in_compute_V_V_4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0))) begin
        in_compute_V_V_4_read = 1'b1;
    end else begin
        in_compute_V_V_4_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_compute_V_V_5_blk_n = in_compute_V_V_5_empty_n;
    end else begin
        in_compute_V_V_5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0))) begin
        in_compute_V_V_5_read = 1'b1;
    end else begin
        in_compute_V_V_5_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_compute_V_V_6_blk_n = in_compute_V_V_6_empty_n;
    end else begin
        in_compute_V_V_6_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0))) begin
        in_compute_V_V_6_read = 1'b1;
    end else begin
        in_compute_V_V_6_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_compute_V_V_7_blk_n = in_compute_V_V_7_empty_n;
    end else begin
        in_compute_V_V_7_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0))) begin
        in_compute_V_V_7_read = 1'b1;
    end else begin
        in_compute_V_V_7_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_compute_V_V_8_blk_n = in_compute_V_V_8_empty_n;
    end else begin
        in_compute_V_V_8_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0))) begin
        in_compute_V_V_8_read = 1'b1;
    end else begin
        in_compute_V_V_8_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_compute_V_V_9_blk_n = in_compute_V_V_9_empty_n;
    end else begin
        in_compute_V_V_9_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_1545 == 1'd0))) begin
        in_compute_V_V_9_read = 1'b1;
    end else begin
        in_compute_V_V_9_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (tmp_19_i_reg_1558_pp0_iter3_reg == 1'd1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_sqrt_V_V_blk_n = in_sqrt_V_V_full_n;
    end else begin
        in_sqrt_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op201_write_state6 == 1'b1))) begin
        in_sqrt_V_V_write = 1'b1;
    end else begin
        in_sqrt_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        mean_pipe1_V_V_blk_n = mean_pipe1_V_V_empty_n;
    end else begin
        mean_pipe1_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op45_read_state3 == 1'b1))) begin
        mean_pipe1_V_V_read = 1'b1;
    end else begin
        mean_pipe1_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        n_pipe1_V_V_blk_n = n_pipe1_V_V_empty_n;
    end else begin
        n_pipe1_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (n_pipe2_V_V_full_n == 1'b0) | (n_pipe1_V_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        n_pipe1_V_V_read = 1'b1;
    end else begin
        n_pipe1_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        n_pipe2_V_V_blk_n = n_pipe2_V_V_full_n;
    end else begin
        n_pipe2_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (n_pipe2_V_V_full_n == 1'b0) | (n_pipe1_V_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        n_pipe2_V_V_write = 1'b1;
    end else begin
        n_pipe2_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (n_pipe2_V_V_full_n == 1'b0) | (n_pipe1_V_V_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((in_sqrt_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op201_write_state6 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((mean_pipe1_V_V_empty_n == 1'b0) & (ap_predicate_op45_read_state3 == 1'b1)) | ((in_compute_V_V_15_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_14_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_13_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_12_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_11_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_10_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_9_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_8_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_7_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_6_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_5_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_4_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_3_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_2_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_1_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_0_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((in_sqrt_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op201_write_state6 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((mean_pipe1_V_V_empty_n == 1'b0) & (ap_predicate_op45_read_state3 == 1'b1)) | ((in_compute_V_V_15_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_14_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_13_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_12_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_11_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_10_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_9_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_8_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_7_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_6_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_5_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_4_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_3_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_2_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_1_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_0_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((in_sqrt_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (ap_predicate_op201_write_state6 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((mean_pipe1_V_V_empty_n == 1'b0) & (ap_predicate_op45_read_state3 == 1'b1)) | ((in_compute_V_V_15_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_14_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_13_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_12_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_11_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_10_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_9_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_8_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_7_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_6_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_5_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_4_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_3_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_2_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_1_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_0_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)))));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (n_pipe2_V_V_full_n == 1'b0) | (n_pipe1_V_V_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((mean_pipe1_V_V_empty_n == 1'b0) & (ap_predicate_op45_read_state3 == 1'b1)) | ((in_compute_V_V_15_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_14_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_13_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_12_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_11_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_10_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_9_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_8_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_7_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_6_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_5_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_4_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_3_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_2_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_1_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)) | ((in_compute_V_V_0_empty_n == 1'b0) & (exitcond_flatten_reg_1545 == 1'd0)));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter4 = ((in_sqrt_V_V_full_n == 1'b0) & (ap_predicate_op201_write_state6 == 1'b1));
end

always @ (*) begin
    ap_condition_480 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0));
end

always @ (*) begin
    ap_condition_502 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_p_0111_2_i_reg_869 = 'bx;

assign ap_phi_reg_pp0_iter0_var_V_0_2_i_reg_677 = 'bx;

assign ap_phi_reg_pp0_iter0_var_V_10_2_i_reg_797 = 'bx;

assign ap_phi_reg_pp0_iter0_var_V_11_2_i_reg_809 = 'bx;

assign ap_phi_reg_pp0_iter0_var_V_12_2_i_reg_821 = 'bx;

assign ap_phi_reg_pp0_iter0_var_V_13_2_i_reg_833 = 'bx;

assign ap_phi_reg_pp0_iter0_var_V_14_2_i_reg_845 = 'bx;

assign ap_phi_reg_pp0_iter0_var_V_15_2_i_reg_857 = 'bx;

assign ap_phi_reg_pp0_iter0_var_V_1_2_i_reg_689 = 'bx;

assign ap_phi_reg_pp0_iter0_var_V_2_2_i_reg_701 = 'bx;

assign ap_phi_reg_pp0_iter0_var_V_3_2_i_reg_713 = 'bx;

assign ap_phi_reg_pp0_iter0_var_V_4_2_i_reg_725 = 'bx;

assign ap_phi_reg_pp0_iter0_var_V_5_2_i_reg_737 = 'bx;

assign ap_phi_reg_pp0_iter0_var_V_6_2_i_reg_749 = 'bx;

assign ap_phi_reg_pp0_iter0_var_V_7_2_i_reg_761 = 'bx;

assign ap_phi_reg_pp0_iter0_var_V_8_2_i_reg_773 = 'bx;

assign ap_phi_reg_pp0_iter0_var_V_9_2_i_reg_785 = 'bx;

assign ap_phi_reg_pp0_iter4_p_0111_4_i_reg_881 = 'bx;

always @ (*) begin
    ap_predicate_op201_write_state6 = ((tmp_19_i_reg_1558_pp0_iter3_reg == 1'd1) & (exitcond_flatten_reg_1545_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op45_read_state3 = ((tmp_18_i_reg_1554 == 1'd1) & (exitcond_flatten_reg_1545 == 1'd0));
end

assign ap_ready = internal_ap_ready;

assign bound_fu_913_p2 = (p_shl_fu_893_p3 - p_shl2_fu_909_p1);

assign exitcond_flatten_fu_919_p2 = ((indvar_flatten_reg_467 == bound_reg_1540) ? 1'b1 : 1'b0);

assign in_sqrt_V_V_din = (tmp21_fu_1520_p2 + tmp14_fu_1490_p2);

assign indvar_flatten_next_fu_924_p2 = (indvar_flatten_reg_467 + 38'd1);

assign l_fu_956_p2 = (l_i_mid2_fu_936_p3 + 6'd1);

assign l_i_mid2_fu_936_p3 = ((tmp_i3_fu_930_p2[0:0] === 1'b1) ? 6'd0 : l_i_reg_478);

assign n_pipe2_V_V_din = n_pipe1_V_V_dout;

assign p_3_10_i_fu_1397_p0 = y_11_V_fu_1267_p1;

assign p_3_10_i_fu_1397_p1 = y_11_V_fu_1267_p1;

assign p_3_10_i_fu_1397_p2 = ($signed(p_3_10_i_fu_1397_p0) * $signed(p_3_10_i_fu_1397_p1));

assign p_3_11_i_fu_1409_p0 = y_12_V_fu_1270_p1;

assign p_3_11_i_fu_1409_p1 = y_12_V_fu_1270_p1;

assign p_3_11_i_fu_1409_p2 = ($signed(p_3_11_i_fu_1409_p0) * $signed(p_3_11_i_fu_1409_p1));

assign p_3_12_i_fu_1421_p0 = y_13_V_fu_1273_p1;

assign p_3_12_i_fu_1421_p1 = y_13_V_fu_1273_p1;

assign p_3_12_i_fu_1421_p2 = ($signed(p_3_12_i_fu_1421_p0) * $signed(p_3_12_i_fu_1421_p1));

assign p_3_13_i_fu_1433_p0 = y_14_V_fu_1276_p1;

assign p_3_13_i_fu_1433_p1 = y_14_V_fu_1276_p1;

assign p_3_13_i_fu_1433_p2 = ($signed(p_3_13_i_fu_1433_p0) * $signed(p_3_13_i_fu_1433_p1));

assign p_3_14_i_fu_1234_p0 = r_V_i_fu_1218_p1;

assign p_3_14_i_fu_1234_p1 = r_V_i_fu_1218_p1;

assign p_3_14_i_fu_1234_p2 = ($signed(p_3_14_i_fu_1234_p0) * $signed(p_3_14_i_fu_1234_p1));

assign p_3_1_i_fu_1291_p0 = y_1_V_fu_1243_p1;

assign p_3_1_i_fu_1291_p1 = y_1_V_fu_1243_p1;

assign p_3_1_i_fu_1291_p2 = ($signed(p_3_1_i_fu_1291_p0) * $signed(p_3_1_i_fu_1291_p1));

assign p_3_2_i_fu_1303_p0 = y_2_V_fu_1246_p1;

assign p_3_2_i_fu_1303_p1 = y_2_V_fu_1246_p1;

assign p_3_2_i_fu_1303_p2 = ($signed(p_3_2_i_fu_1303_p0) * $signed(p_3_2_i_fu_1303_p1));

assign p_3_3_i_fu_1315_p0 = y_3_V_fu_1249_p1;

assign p_3_3_i_fu_1315_p1 = y_3_V_fu_1249_p1;

assign p_3_3_i_fu_1315_p2 = ($signed(p_3_3_i_fu_1315_p0) * $signed(p_3_3_i_fu_1315_p1));

assign p_3_4_i_fu_1327_p0 = y_4_V_fu_1252_p1;

assign p_3_4_i_fu_1327_p1 = y_4_V_fu_1252_p1;

assign p_3_4_i_fu_1327_p2 = ($signed(p_3_4_i_fu_1327_p0) * $signed(p_3_4_i_fu_1327_p1));

assign p_3_5_i_fu_1222_p0 = y_5_V_fu_1060_p1;

assign p_3_5_i_fu_1222_p1 = y_5_V_fu_1060_p1;

assign p_3_5_i_fu_1222_p2 = ($signed(p_3_5_i_fu_1222_p0) * $signed(p_3_5_i_fu_1222_p1));

assign p_3_6_i_fu_1228_p0 = y_6_V_fu_1079_p1;

assign p_3_6_i_fu_1228_p1 = y_6_V_fu_1079_p1;

assign p_3_6_i_fu_1228_p2 = ($signed(p_3_6_i_fu_1228_p0) * $signed(p_3_6_i_fu_1228_p1));

assign p_3_7_i_fu_1349_p0 = y_7_V_fu_1255_p1;

assign p_3_7_i_fu_1349_p1 = y_7_V_fu_1255_p1;

assign p_3_7_i_fu_1349_p2 = ($signed(p_3_7_i_fu_1349_p0) * $signed(p_3_7_i_fu_1349_p1));

assign p_3_8_i_fu_1361_p0 = y_8_V_fu_1258_p1;

assign p_3_8_i_fu_1361_p1 = y_8_V_fu_1258_p1;

assign p_3_8_i_fu_1361_p2 = ($signed(p_3_8_i_fu_1361_p0) * $signed(p_3_8_i_fu_1361_p1));

assign p_3_9_i_fu_1373_p0 = y_9_V_fu_1261_p1;

assign p_3_9_i_fu_1373_p1 = y_9_V_fu_1261_p1;

assign p_3_9_i_fu_1373_p2 = ($signed(p_3_9_i_fu_1373_p0) * $signed(p_3_9_i_fu_1373_p1));

assign p_3_i_35_fu_1385_p0 = y_10_V_fu_1264_p1;

assign p_3_i_35_fu_1385_p1 = y_10_V_fu_1264_p1;

assign p_3_i_35_fu_1385_p2 = ($signed(p_3_i_35_fu_1385_p0) * $signed(p_3_i_35_fu_1385_p1));

assign p_3_i_fu_1279_p0 = y_0_V_fu_1240_p1;

assign p_3_i_fu_1279_p1 = y_0_V_fu_1240_p1;

assign p_3_i_fu_1279_p2 = ($signed(p_3_i_fu_1279_p0) * $signed(p_3_i_fu_1279_p1));

assign p_shl2_fu_909_p1 = tmp_fu_901_p3;

assign p_shl_fu_893_p3 = {{n_pipe1_V_V_dout}, {6'd0}};

assign r_V_i_fu_1218_p1 = $signed(tmp_114_i_fu_1208_p4);

assign read_V_10_i_fu_1143_p2 = (tmp_V_104_reg_1622 - tmp_V_fu_340);

assign read_V_11_i_fu_1158_p2 = (tmp_V_105_reg_1627 - tmp_V_fu_340);

assign read_V_12_i_fu_1173_p2 = (tmp_V_106_reg_1632 - tmp_V_fu_340);

assign read_V_13_i_fu_1188_p2 = (tmp_V_107_reg_1637 - tmp_V_fu_340);

assign read_V_14_i_fu_1203_p2 = (tmp_V_108_reg_1642 - tmp_V_fu_340);

assign read_V_1_i_fu_985_p2 = (tmp_V_94_reg_1572 - tmp_V_fu_340);

assign read_V_2_i_fu_1000_p2 = (tmp_V_95_reg_1577 - tmp_V_fu_340);

assign read_V_3_i_fu_1015_p2 = (tmp_V_96_reg_1582 - tmp_V_fu_340);

assign read_V_4_i_fu_1030_p2 = (tmp_V_97_reg_1587 - tmp_V_fu_340);

assign read_V_5_i_fu_1045_p2 = (tmp_V_98_reg_1592 - tmp_V_fu_340);

assign read_V_6_i_fu_1064_p2 = (tmp_V_99_reg_1597 - tmp_V_fu_340);

assign read_V_7_i_fu_1083_p2 = (tmp_V_100_reg_1602 - tmp_V_fu_340);

assign read_V_8_i_fu_1098_p2 = (tmp_V_101_reg_1607 - tmp_V_fu_340);

assign read_V_9_i_fu_1113_p2 = (tmp_V_102_reg_1612 - tmp_V_fu_340);

assign read_V_i_34_fu_1128_p2 = (tmp_V_103_reg_1617 - tmp_V_fu_340);

assign read_V_i_fu_970_p2 = (tmp_V_93_reg_1567 - tmp_V_fu_340);

assign start_out = real_start;

assign tmp14_fu_1490_p2 = (tmp18_fu_1484_p2 + tmp15_fu_1470_p2);

assign tmp15_fu_1470_p2 = (tmp17_fu_1466_p2 + tmp16_fu_1462_p2);

assign tmp16_fu_1462_p2 = (var_13_V_reg_1803 + var_14_V_reg_1809);

assign tmp17_fu_1466_p2 = (var_12_V_reg_1797 + var_11_V_reg_1791);

assign tmp18_fu_1484_p2 = (tmp20_fu_1480_p2 + tmp19_fu_1476_p2);

assign tmp19_fu_1476_p2 = (var_8_V_reg_1773 + var_7_V_reg_1767);

assign tmp20_fu_1480_p2 = (var_10_V_reg_1785 + var_9_V_reg_1779);

assign tmp21_fu_1520_p2 = (tmp25_fu_1515_p2 + tmp22_fu_1505_p2);

assign tmp22_fu_1505_p2 = (tmp24_fu_1501_p2 + tmp23_fu_1496_p2);

assign tmp23_fu_1496_p2 = (var_0_V_reg_1727 + ap_phi_reg_pp0_iter4_p_0111_2_i_reg_869);

assign tmp24_fu_1501_p2 = (var_2_V_reg_1739 + var_1_V_reg_1733);

assign tmp25_fu_1515_p2 = (tmp27_reg_1820 + tmp26_fu_1511_p2);

assign tmp26_fu_1511_p2 = (var_4_V_reg_1751 + var_3_V_reg_1745);

assign tmp27_fu_1456_p2 = (tmp28_fu_1450_p2 + var_6_V_fu_1344_p2);

assign tmp28_fu_1450_p2 = (var_5_V_fu_1339_p2 + var_15_V_fu_1445_p2);

assign tmp_114_i_fu_1208_p4 = {{read_V_14_i_fu_1203_p2[31:6]}};

assign tmp_18_i_fu_944_p2 = ((l_i_mid2_fu_936_p3 == 6'd0) ? 1'b1 : 1'b0);

assign tmp_19_i_fu_950_p2 = ((l_i_mid2_fu_936_p3 == 6'd47) ? 1'b1 : 1'b0);

assign tmp_94_i_fu_1050_p4 = {{read_V_5_i_fu_1045_p2[31:6]}};

assign tmp_96_i_fu_1069_p4 = {{read_V_6_i_fu_1064_p2[31:6]}};

assign tmp_V_109_fu_1526_p2 = (tmp21_fu_1520_p2 + tmp14_fu_1490_p2);

assign tmp_fu_901_p3 = {{n_pipe1_V_V_dout}, {4'd0}};

assign tmp_i3_fu_930_p2 = ((l_i_reg_478 == 6'd48) ? 1'b1 : 1'b0);

assign var_0_V_fu_1285_p2 = (p_3_i_fu_1279_p2 + ap_phi_mux_var_V_0_2_i_phi_fu_681_p4);

assign var_10_V_fu_1391_p2 = (p_3_i_35_fu_1385_p2 + ap_phi_mux_var_V_10_2_i_phi_fu_801_p4);

assign var_11_V_fu_1403_p2 = (p_3_10_i_fu_1397_p2 + ap_phi_mux_var_V_11_2_i_phi_fu_813_p4);

assign var_12_V_fu_1415_p2 = (p_3_11_i_fu_1409_p2 + ap_phi_mux_var_V_12_2_i_phi_fu_825_p4);

assign var_13_V_fu_1427_p2 = (p_3_12_i_fu_1421_p2 + ap_phi_mux_var_V_13_2_i_phi_fu_837_p4);

assign var_14_V_fu_1439_p2 = (p_3_13_i_fu_1433_p2 + ap_phi_mux_var_V_14_2_i_phi_fu_849_p4);

assign var_15_V_fu_1445_p2 = (p_3_14_i_reg_1722 + ap_phi_mux_var_V_15_2_i_phi_fu_861_p4);

assign var_1_V_fu_1297_p2 = (p_3_1_i_fu_1291_p2 + ap_phi_mux_var_V_1_2_i_phi_fu_693_p4);

assign var_2_V_fu_1309_p2 = (p_3_2_i_fu_1303_p2 + ap_phi_mux_var_V_2_2_i_phi_fu_705_p4);

assign var_3_V_fu_1321_p2 = (p_3_3_i_fu_1315_p2 + ap_phi_mux_var_V_3_2_i_phi_fu_717_p4);

assign var_4_V_fu_1333_p2 = (p_3_4_i_fu_1327_p2 + ap_phi_mux_var_V_4_2_i_phi_fu_729_p4);

assign var_5_V_fu_1339_p2 = (p_3_5_i_reg_1712 + ap_phi_mux_var_V_5_2_i_phi_fu_741_p4);

assign var_6_V_fu_1344_p2 = (p_3_6_i_reg_1717 + ap_phi_mux_var_V_6_2_i_phi_fu_753_p4);

assign var_7_V_fu_1355_p2 = (p_3_7_i_fu_1349_p2 + ap_phi_mux_var_V_7_2_i_phi_fu_765_p4);

assign var_8_V_fu_1367_p2 = (p_3_8_i_fu_1361_p2 + ap_phi_mux_var_V_8_2_i_phi_fu_777_p4);

assign var_9_V_fu_1379_p2 = (p_3_9_i_fu_1373_p2 + ap_phi_mux_var_V_9_2_i_phi_fu_789_p4);

assign y_0_V_fu_1240_p1 = $signed(tmp_84_i_reg_1647);

assign y_10_V_fu_1264_p1 = $signed(tmp_104_i_reg_1687);

assign y_11_V_fu_1267_p1 = $signed(tmp_106_i_reg_1692);

assign y_12_V_fu_1270_p1 = $signed(tmp_108_i_reg_1697);

assign y_13_V_fu_1273_p1 = $signed(tmp_110_i_reg_1702);

assign y_14_V_fu_1276_p1 = $signed(tmp_112_i_reg_1707);

assign y_1_V_fu_1243_p1 = $signed(tmp_86_i_reg_1652);

assign y_2_V_fu_1246_p1 = $signed(tmp_88_i_reg_1657);

assign y_3_V_fu_1249_p1 = $signed(tmp_90_i_reg_1662);

assign y_4_V_fu_1252_p1 = $signed(tmp_92_i_reg_1667);

assign y_5_V_fu_1060_p1 = $signed(tmp_94_i_fu_1050_p4);

assign y_6_V_fu_1079_p1 = $signed(tmp_96_i_fu_1069_p4);

assign y_7_V_fu_1255_p1 = $signed(tmp_98_i_reg_1672);

assign y_8_V_fu_1258_p1 = $signed(tmp_100_i_reg_1677);

assign y_9_V_fu_1261_p1 = $signed(tmp_102_i_reg_1682);

always @ (posedge ap_clk) begin
    bound_reg_1540[3:0] <= 4'b0000;
end

endmodule //layernorm_compute_va
